// Bottleneko.Client/src/features/connections/add-wizard/AddConnectionFinish.tsx
import { Alert } from 'react-bootstrap';
import { useCallback, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import Highlight from 'react-highlight';
import { ConnectionDefinition } from '..';
import { useAsync, useOnceEffect } from '../../../app/hooks';
import { useConnections } from '../context';
import { WizardNavigation } from '../../../components/WizardNavigation';
import { ErrorMetadata, extractErrorInfo } from '../../../app/utils';
import { Protocol } from '../../api/dtos.gen';
import { AddConnectionStage } from './AddConnectionView';

export default function AddConnectionFinish({ definition, setStage }: { protocol: Protocol; definition: ConnectionDefinition; setStage: (stage: AddConnectionStage) => void }) {
    const [error, setError] = useState<ErrorMetadata | null>();
    const connections = useConnections();
    const navigate = useNavigate();

    const onError = useCallback((err: unknown) => {
        setError(extractErrorInfo(err));
    }, []);

    const [addConnection, isLoading] = useAsync(useCallback(async () => {
        if (!connections) {
            return;
        }

        const newConnection = (await connections.actions.add({ name: definition.name, config: definition.config })).result;
        await navigate(`/connections/${newConnection.id}`);
    }, [definition, connections, navigate]));

    useOnceEffect(() => {
        addConnection().catch(onError);
    });

    return (
        <>
            {
                isLoading
                    ? (
                            <Alert variant="primary">
                                <span className="fs-4">Adding new connection...</span>
                            </Alert>
                        )
                    : (
                            <Alert variant="danger">
                                <p className="fs-4">Failed to add connection</p>

                                <Highlight className="json">{JSON.stringify(error, null, 2)}</Highlight>
                            </Alert>
                        )
            }
            <WizardNavigation back={isLoading ? undefined : () => { setStage({ stage: 'config', definition }); }} />
        </>
    );
}

// src/Bottleneko.Client/src/routes/connections/add/[protocol]/AddConnectionFinish.svelte
<script lang="ts">
    import WizardNavigation from '$lib/components/WizardNavigation.svelte';
    import { Connections } from '$lib/features/connections';
    import { onMount } from 'svelte';
    import { extractErrorInfo, type ErrorMetadata } from '$lib';
    import { Alert } from '@sveltestrap/sveltestrap';
    import Highlight from 'svelte-highlight';
    import json from 'svelte-highlight/languages/json';
    import { goto } from '$app/navigation';
    import { resolve } from '$app/paths';
    import type { Props } from './AddConnectionFinish';

    const props: Props = $props();
    let error: ErrorMetadata | null = $state(null);
    let isLoading = $state(true);

    onMount(async () => {
        if (!Connections.provider) {
            await goto(resolve('/'));
            return;
        }

        try {
            const connection = await Connections.provider.add(props.definition);
            await goto(resolve('/connections/[connectionId]', { connectionId: connection.data.id }));
        } catch (err: unknown) {
            error = extractErrorInfo(err);
        } finally {
            isLoading = false;
        }
    });
</script>

<div>
    {#if isLoading}
        <Alert color="primary" class="w-100">
            <span class="fs-4">Adding new connection...</span>
        </Alert>
    {:else if error}
        <Alert color="danger" class="w-100">
            <p class="fs-4">Failed to add connection</p>

            <Highlight language={json} code={JSON.stringify(error, null, 2)} />
        </Alert>
    {/if}
    <WizardNavigation
        back={!isLoading && error
            ? () => {
                  props.onstagechange?.({ id: 'config', protocol: props.protocol, definition: props.definition });
              }
            : undefined}
    />
</div>
