// Bottleneko.Client/src/features/messages/MessageConnectionDisplay.tsx
import { Link } from 'react-router-dom';
import { Button, OverlayTrigger, Tooltip } from 'react-bootstrap';
import { useConnections } from '../connections/context';
import ProtocolIcon from '../connections/ProtocolIcon';

export default function MessageConnectionDisplay({ connectionId }: { connectionId: string }) {
    const connections = useConnections();
    const connection = connections?.state.list?.find(connection => connection.data.id === connectionId);

    if (connection) {
        return (
            <Link to={`/connections/${connectionId}`} className="btn btn-primary btn-sm px-1 py-0">
                <ProtocolIcon protocol={connection.data.protocol} />
                {' '}
                {connection.data.name}
            </Link>
        );
    }
    else {
        const renderTooltip = (props: object) => <Tooltip {...props}>The connection does not exist or has been deleted.</Tooltip>;
        return (
            <OverlayTrigger placement="bottom" overlay={renderTooltip}>
                <Button variant="primary" size="sm" className="px-1 py-0" disabled>
                    {'Connection #' + connectionId}
                </Button>
            </OverlayTrigger>
        );
    }
}

// src/Bottleneko.Client/src/lib/features/messages/MessageConnectionDisplay.svelte
<script lang="ts">
    import { Button, Tooltip } from '@sveltestrap/sveltestrap';

    import { Connections } from '../connections';
    import ProtocolIcon from '../connections/ProtocolIcon.svelte';
    import { resolve } from '$app/paths';
    import type { Props } from './MessageConnectionDisplay';

    const { variant = 'primary', ...props }: Props = $props();

    const connection = $derived(
        Connections.provider?.list?.find((connection) => props.connectionId === connection.data.id),
    );
    let button: HTMLElement | undefined = $state();
</script>

{#if connection}
    <Button
        href={resolve('/connections/[connectionId]', { connectionId: connection.data.id })}
        size="sm"
        color={variant}
        class="px-1 py-0 text-collapse"
        style={props.style}
    >
        <div bind:this={button}>
            <ProtocolIcon protocol={connection.data.protocol} />
            {connection.data.name}
        </div>
    </Button>

    <Tooltip target={button} theme="light" placement="bottom" delay="250">
        {connection.data.name}
    </Tooltip>
{:else}
    <Button color="primary" size="sm" style={props.style} class="px-1 py-0 text-collapse" disabled>
        <div bind:this={button}>
            Connection #{props.connectionId ?? '?'}
        </div>
    </Button>

    <Tooltip target={button} theme="light" placement="bottom" delay="250">
        The connection does not exist or has been deleted.
    </Tooltip>
{/if}
