// Bottleneko.Client/src/features/messages/MessageHistoryViewer.tsx
﻿import './MessageHistoryViewer.css';
import { Button, Card, Table } from 'react-bootstrap';
import dateFormat from 'dateformat';
import { useSubscription } from '../websockets/hooks';
import { ChatMessageLetter } from '../api/dtos.gen';
import api from '../api';
import LoadingBanner from '../../components/LoadingBanner';
import MessageConnectionDisplay from './MessageConnectionDisplay';

export default function MessageHistoryViewer({ className, connectionId }: { className?: string; connectionId?: string }) {
    const { events } = useSubscription<ChatMessageLetter>({
        subscription: {
            type: 'ChatMessages',
            filter: {
                connectionId: connectionId ?? null,
            },
        },
        maxEvents: 250,
    });

    return (
        <>
            <Card className={className ?? ''} style={{ margin: '0.5em' }}>
                <Card.Body className="d-flex flex-column h-100" style={{ gap: '1em' }}>
                    <div className="flex-grow-1" style={{ overflowY: 'scroll' }}>
                        <Table style={{ minWidth: '50em' }} size="sm" className="message-history-viewer">
                            <thead>
                                <tr>
                                    <th>Timestamp</th>
                                    {
                                        !connectionId
                                            ? <th>Connection</th>
                                            : <></>
                                    }
                                    <th>Chat</th>
                                    <th>Author</th>
                                    <th>Message</th>
                                    <th>Attachments</th>
                                </tr>
                            </thead>
                            <tbody>
                                {events && events.length > 0
                                    ? events.map(message => (
                                            <tr key={message.content.id} className={`message-history-message ${message.content.isDirect ? 'message-history-direct' : 'message-history-normal'}`}>
                                                <td className="message-history-timestamp font-monospace">{dateFormat(new Date(message.content.timestamp), 'yyyy-mm-dd HH:MM:ss')}</td>
                                                {
                                                    !connectionId
                                                        ? (
                                                                <td className="message-history-connection">
                                                                    <MessageConnectionDisplay connectionId={message.content.connectionId} />
                                                                </td>
                                                            )
                                                        : <></>
                                                }
                                                <td className="message-history-chat message-history-clip">{message.content.chat.name}</td>
                                                <td className="message-history-author message-history-clip">{message.content.author.name}</td>
                                                <td className={`message-history-content ${message.content.textContent ? '' : 'text-secondary'}`}>{message.content.textContent ?? '(no text)'}</td>
                                                <td className="message-history-attachments">
                                                    <div className="d-flex flex-column" style={{ gap: '0.5rem' }}>
                                                        {
                                                            message.content.attachments.map(attachment => (
                                                                <Button key={attachment.id} className="w-100" size="sm" as="a" target="_blank" rel="noreferrer" href={api.connections.getAttachmentUrl(message.content.connectionId, attachment.id)}>
                                                                    {attachment.name ?? 'no name'}
                                                                </Button>
                                                            ))
                                                        }
                                                    </div>
                                                </td>
                                            </tr>
                                        ))
                                    : (
                                            <tr>
                                                <td colSpan={!connectionId ? 6 : 5} className="text-center">
                                                    {
                                                        events
                                                            ? <em className="text-secondary fst-italic">(no messages)</em>
                                                            : <LoadingBanner />
                                                    }
                                                </td>
                                            </tr>
                                        )}
                            </tbody>
                        </Table>
                    </div>
                </Card.Body>
            </Card>
        </>
    );
}

// src/Bottleneko.Client/src/lib/features/messages/MessageHistoryViewer.svelte
<script lang="ts">
    import { blur } from 'svelte/transition';
    import { flip } from 'svelte/animate';
    import { ChatMessagesSubscriber } from '../ws/WebSocketConnection.svelte';
    import type { Props } from './MessageHistoryViewer';
    import { Button, Card, CardBody, CardFooter, CardHeader } from '@sveltestrap/sveltestrap';
    import dateFormat from 'dateformat';
    import api from '$lib/api';
    import MessageConnectionDisplay from './MessageConnectionDisplay.svelte';
    import IconButton from '$lib/components/IconButton.svelte';
    import InlineIcon from '$lib/components/InlineIcon.svelte';
    import LoadingBanner from '$lib/components/LoadingBanner.svelte';

    const props: Props = $props();

    const subscriber = new ChatMessagesSubscriber();
    $effect(() => {
        subscriber.subscribe({ connectionId: props.connectionId ?? null, protocol: null });
    });
</script>

<div style="overflow-y: scroll" class="h-100 card p-1">
    {#if subscriber.mail.length > 0}
        {#each subscriber.mail as letter (letter.content.id)}
            <div
                class="mb-2"
                style="max-width: 600px; width: 100%"
                in:blur|global={{ duration: 300 }}
                animate:flip={{ duration: 300 }}
            >
                <Card class="w-100 border-light border-opacity-25 shadow">
                    <CardHeader class="py-1 px-2">
                        <div class="d-flex flex-row align-items-center" style="gap: 0.5em; height: 2em">
                            <div class="text-collapse">
                                {#if letter.content.isDirect}
                                    <span
                                        ><strong>Direct message</strong> from
                                        <strong>{letter.content.author.displayName}</strong></span
                                    >
                                {:else}
                                    <span
                                        ><strong>{letter.content.author.displayName}</strong> in
                                        <strong>{letter.content.chat.displayName}</strong></span
                                    >
                                {/if}
                            </div>
                            <div class="ms-auto d-flex" style:gap="0.25em">
                                {#if letter.content.isSpecial}
                                    <IconButton
                                        icon="patch-exclamation"
                                        variant="warning"
                                        tooltip="Special message"
                                        size="2em"
                                    />
                                {/if}
                                {#if letter.content.isDirect}
                                    <IconButton
                                        icon="chat-square-dots-fill"
                                        variant="primary"
                                        tooltip="Direct message"
                                        size="2em"
                                    />
                                {/if}
                            </div>
                        </div>
                    </CardHeader>
                    <CardBody class="pd-3">
                        <div class="d-flex flex-column" style:gap="1em">
                            <div>
                                {#if letter.content.textContent === null || letter.content.textContent === ''}
                                    <p class="text-secondary m-0" style="text-align: center">(no text)</p>
                                {:else}
                                    <p class="m-0">
                                        {letter.content.textContent}
                                    </p>
                                {/if}
                            </div>
                            {#if letter.content.attachments.length > 0}
                                <div class="d-flex flex-column" style:gap="0.25em">
                                    {#each letter.content.attachments as attachment (attachment.id)}
                                        <Button
                                            size="sm"
                                            target="_blank"
                                            rel="noreferrer"
                                            color="primary"
                                            class="text-collapse"
                                            href={api.connections.getAttachmentUrl(
                                                letter.content.connectionId,
                                                attachment.id,
                                            )}
                                        >
                                            <InlineIcon icon="file-earmark-arrow-down-fill" />
                                            {attachment.name ?? 'no name'}
                                        </Button>
                                    {/each}
                                </div>
                            {/if}
                        </div>
                    </CardBody>

                    <CardFooter class="d-flex flex-row px-2 align-items-center" style="gap: 0.5em; height: 2em">
                        {#if props.connectionId === undefined}
                            <MessageConnectionDisplay
                                style="max-width: 50%"
                                variant="primary"
                                connectionId={letter.content.connectionId}
                            />
                        {/if}
                        <small class="text-secondary ms-auto"
                            >{dateFormat(new Date(letter.content.timestamp), 'yyyy-mm-dd HH:MM:ss')}</small
                        >
                    </CardFooter>
                </Card>
            </div>
        {/each}
    {:else if !subscriber.isLoading}
        <div class="w-100 h-100 d-flex justify-content-center align-items-center">
            <p class="text-secondary" style="text-align: center">(no messages)</p>
        </div>
    {:else}
        <LoadingBanner size="lg" />
    {/if}
</div>
