// Bottleneko.Client/src/features/connections/ConnectionList.tsx
import { useCallback } from 'react';
import { Form } from 'react-bootstrap';
import { useNavigate } from 'react-router-dom';
import { LinkContainer } from 'react-router-bootstrap';
import ScrollableTable from '../../components/table/ScrollableTable';
import StateControlButtons from '../../components/StateControlButtons';
import IconButton from '../../components/IconButton';
import { TableRow } from '../../components/table';
import { useConnections } from './context';
import ProtocolIcon from './ProtocolIcon';
import ConnectionStatusIcon from './ConnectionStatusIcon';
import { ConnectionState } from './ConnectionsProvider';

export default function ConnectionList({ onDelete }: { onDelete: (connection: ConnectionState) => void }) {
    const connections = useConnections();
    const navigate = useNavigate();

    const columns = [
        { id: 'name', header: 'Connection Name', className: 'text-collapse' },
        { id: 'status', header: 'Status', style: { width: '10em' } },
        { id: 'autostart', header: 'Auto Start', style: { width: '7em' } },
        { id: 'actions', header: '', style: { width: '8em' } },
    ];

    const renderRow = useCallback((connection: ConnectionState): TableRow => ({
        id: connection.data.id,
        onClick: () => { navigate(`/connections/${connection.data.id}`); },
        columns: {
            name: {
                content: (
                    <>
                        <ProtocolIcon protocol={connection.data.protocol} />
                        {' '}
                        {connection.data.name}
                    </>
                ),
                className: 'text-collapse',
                style: { verticalAlign: 'middle' },
            },
            status: {
                content: <ConnectionStatusIcon status={connection.data.extendedStatus} showLabel />,
                style: { verticalAlign: 'middle' },
            },
            autostart: {
                content: <Form.Switch style={{ fontSize: '1.25em' }} checked={connection.data.autoStart} disabled={connection.isLoading} onChange={() => { void connection.setAutoStart(!connection.data.autoStart); }} />,
                onClick: (e) => { e.stopPropagation(); },
            },
            actions: {
                content: (
                    <div className="w-100">
                        <StateControlButtons
                            canStart={connection.canStart}
                            onStart={() => { void connection.start(); }}
                            startTooltip="Connect"

                            canRestart={connection.canRestart}
                            onRestart={() => { void connection.restart(); }}
                            restartTooltip="Reconnect"

                            canStop={connection.canStop}
                            onStop={() => { void connection.stop(); }}
                            stopTooltip="Disconnect"

                            canDelete={true}
                            onDelete={() => { onDelete(connection); }}

                            size="2em"
                        />
                    </div>
                ),
                onClick: (e) => { e.stopPropagation(); },
            },
        },
    }), [navigate, onDelete]);

    return (
        <div className="connection-list h-100">
            <ScrollableTable<ConnectionState>
                columns={columns}
                render={renderRow}
                data={connections?.state.list}
                placeholder={() => <em className="text-secondary fst-italic">(no connections)</em>}
                title="Connection list"
                className="entity-list"
                highlightHeader
            >
                <ScrollableTable.HeaderExtra position="end">
                    <LinkContainer to="/connections/add">
                        <IconButton icon="plus-lg" tooltip="Add connection" variant="dark" />
                    </LinkContainer>
                </ScrollableTable.HeaderExtra>
            </ScrollableTable>
        </div>
    );
}

// Bottleneko.Client/src/lib/features/connections/ConnectionList.svelte
<script lang="ts">
    import { goto } from '$app/navigation';
    import { resolve } from '$app/paths';
    import { Connections, protocols } from '.';
    import { LocalConnection } from './provider.svelte';
    import EntityDeletionDialog from '$lib/components/EntityDeletionDialog.svelte';
    import { Button, Card, CardBody, CardHeader, Input } from '@sveltestrap/sveltestrap';
    import ProtocolIcon from './ProtocolIcon.svelte';
    import ConnectionStatusIcon from './ConnectionStatusIcon.svelte';
    import StateControlButtons from '$lib/components/StateControlButtons.svelte';
    import MouseBlocker from '$lib/components/MouseBlocker.svelte';

    let deletingConnection: LocalConnection | null = $state(null);
    let isDeleting = $state(false);

    const doDelete = async () => {
        if (deletingConnection) {
            try {
                isDeleting = true;
                await Connections.provider?.delete(deletingConnection);
            } finally {
                isDeleting = false;
                deletingConnection = null;
            }
        }
    };
</script>

<div class="h-100 d-flex flex-column" style="max-width: 600px; width: 100%; gap: 1rem">
    <EntityDeletionDialog
        item={deletingConnection}
        type-name="connection"
        loading={isDeleting}
        ondelete={doDelete}
        onclose={() => (deletingConnection = null)}
    />

    <Button color="primary" href={resolve('/connections/add')}>Add new connection</Button>

    {#if Connections.provider !== null}
        {#each Connections.provider.list as connection (connection.data.id)}
            <Card>
                <CardHeader
                    class="highlight fs-5 d-flex pe-2"
                    style="cursor: pointer"
                    onclick={async () => {
                        await goto(resolve('/connections/[connectionId]', { connectionId: connection.data.id }));
                    }}
                >
                    <ProtocolIcon protocol={connection.data.protocol} />
                    <div class="ms-2 text-collapse">
                        {connection.data.name}
                    </div>
                    <div class="ms-auto">
                        <MouseBlocker>
                            <StateControlButtons
                                entity={connection}
                                startTooltip="Connect"
                                restartTooltip="Reconnect"
                                stopTooltip="Disconnect"
                                startIcon="wifi"
                                stopIcon="wifi-off"
                                ondelete={() => {
                                    deletingConnection = connection;
                                }}
                                size="2em"
                                variant="dark"
                            />
                        </MouseBlocker>
                    </div>
                </CardHeader>
                <CardBody>
                    <div class="d-grid" style="grid-template-columns: 0.5fr 1fr; gap: 0.5em 0">
                        <div>Protocol</div>
                        <div>{protocols[connection.data.protocol].name}</div>
                        <div>Status</div>
                        <div><ConnectionStatusIcon status={connection.data.extendedStatus} show-label /></div>
                        <div>Auto start</div>
                        <div>
                            <Input
                                type="switch"
                                checked={connection.data.autoStart}
                                onchange={async (e: Event & { currentTarget: HTMLElement }) => {
                                    await connection.setAutoStart((e.currentTarget as HTMLInputElement).checked);
                                }}
                            />
                        </div>
                    </div>
                </CardBody>
            </Card>
        {/each}
    {/if}
</div>
