// Bottleneko.Client/src/components/LoadingBanner.tsx
import { Spinner } from 'react-bootstrap';

export default function LoadingBanner({ size }: { size?: 'xl' | 'lg' | 'sm' }) {
    let style = {};
    switch (size) {
        case 'xl':
            style = { width: '5rem', height: '5rem' };
            break;

        case 'lg':
            style = { width: '3rem', height: '3rem' };
            break;

        case 'sm':
            style = { width: '1rem', height: '1rem' };
            break;
    }

    return (
        <div className="d-flex w-100 h-100 justify-content-center align-items-center">
            <Spinner animation="border" style={style} />
        </div>
    );
}

// Bottleneko.Client/src/lib/components/LoadingBanner.svelte
<script lang="ts">
    import { Spinner } from '@sveltestrap/sveltestrap';
    import type { Props } from './LoadingBanner';

    const { size = 'sm' }: Props = $props();
</script>

<div class="container d-flex w-100 h-100 justify-content-center align-items-center">
    <Spinner type="border" class={`loading-spinner-${size}`} />
</div>

<style>
    .container > :global(.loading-spinner-sm) {
        width: 1rem;
        height: 1rem;
    }
    .container > :global(.loading-spinner-lg) {
        width: 3rem;
        height: 3rem;
    }
    .container > :global(.loading-spinner-xl) {
        width: 5rem;
        height: 5rem;
    }
</style>
