// Bottleneko.Client/src/features/auth/LoginPage.tsx
import { Formik } from 'formik';
import { useCallback, useEffect, useRef, useState } from 'react';
import { Form } from 'react-bootstrap';
import * as yup from 'yup';
import api from '../api';
import { RequestError } from '../api/errors';
import { ErrorCode } from '../api/responses';
import { useAsync } from '../../app/hooks';
import FullscreenPage from '../../components/FullscreenPage';
import { branding } from '../../props';
import { useAuth } from './context';
import { saveAccessToken } from '.';

const schema = yup.object().shape({
    login: yup.string().default('').required('Username is required'),
    password: yup.string().default('').required('Password is required'),
});

export default function LoginPage() {
    const formRef = useRef<HTMLFormElement>(null);
    const [loginError, setLoginError] = useState<string | null>(null);
    const auth = useAuth();

    useEffect(() => {
        const timer = setTimeout(() => {
            setLoginError(null);
        }, 1500);

        return () => {
            clearTimeout(timer);
        };
    }, [loginError]);

    const onError = useCallback((err: unknown) => {
        if (err instanceof RequestError) {
            switch (err.code) {
                case ErrorCode.Unauthorized:
                    setLoginError('Invalid username or password');
                    break;

                case ErrorCode.SetupRequired:
                    auth?.actions.setStatus('setup-required');
                    break;

                default:
                    setLoginError('Unknown error');
                    break;
            }
        }
    }, [auth]);

    const [onValidated, isLoading] = useAsync(useCallback(async (formData: yup.InferType<typeof schema>) => {
        saveAccessToken((await api.users.login(formData.login, formData.password)).accessToken);
        void auth?.actions.refreshMe();
    }, [auth]));

    return (
        <Formik validationSchema={schema} onSubmit={(formData) => { void onValidated(formData).catch(onError); }} initialValues={schema.getDefault()} validateOnChange={false}>
            {({ handleSubmit, handleChange, values, errors }) => (
                <Form
                    noValidate
                    onSubmit={(e) => {
                        e.preventDefault();
                        e.stopPropagation();
                        handleSubmit();
                    }}
                    ref={formRef}
                >
                    <FullscreenPage
                        title={loginError ?? `Login to ${branding.plain}`}
                        titleVariant={loginError ? 'danger' : undefined}
                        buttons={[
                            // { key: 'forgot-password', content: 'Forgot password?', variant: 'dark', action: 'submit', disabled: isLoading },
                            { key: 'submit', content: 'Sign in', disabled: isLoading },
                        ]}
                    >
                        <Form.Group className="mb-3">
                            <Form.Label className="fs-5">Username</Form.Label>
                            <Form.Control name="login" value={values.login} onChange={handleChange} isInvalid={!!errors.login} disabled={isLoading} />
                            <Form.Control.Feedback type="invalid">
                                {errors.login}
                            </Form.Control.Feedback>
                        </Form.Group>

                        <Form.Group className="mb-3">
                            <Form.Label className="fs-5">Password</Form.Label>
                            <Form.Control type="password" name="password" value={values.password} onChange={handleChange} isInvalid={!!errors.password} disabled={isLoading} />
                            <Form.Control.Feedback type="invalid">
                                {errors.password}
                            </Form.Control.Feedback>
                        </Form.Group>
                    </FullscreenPage>
                </Form>
            )}
        </Formik>
    );
}

// src/Bottleneko.Client/src/lib/pages/LoginPage.svelte
<script lang="ts">
    import * as yup from 'yup';
    import FullscreenPage from './FullscreenPage.svelte';
    import { brand } from '$lib/props';
    import { Form, FormGroup, Input, Label } from '@sveltestrap/sveltestrap';
    import api from '$lib/api';
    import { authState, login } from '$lib/features/auth.svelte';
    import { RequestError } from '$lib/api/errors';
    import { onDestroy } from 'svelte';
    import { FormState } from '$lib/FormState.svelte';

    export const LoginSchema = yup.object().shape({
        login: yup.string().default('').required('Username is required'),
        password: yup.string().default('').required('Password is required'),
    });

    class LoginFormState extends FormState<typeof LoginSchema> {
        showErrorTimer: ReturnType<typeof setTimeout> | null = $state(null);

        constructor() {
            super(LoginSchema);
            onDestroy(this.destroy.bind(this));
        }

        override onRequestError(err: unknown) {
            if (err instanceof RequestError) {
                switch (err.code) {
                    case 'Unauthorized':
                        this.showError('Invalid username or password');
                        return;

                    case 'SetupRequired':
                        authState.data = { status: 'setup-required', me: null };
                        return;
                }
            }

            super.onRequestError(err);
        }

        override showError(err: string | null): void {
            super.showError(err);

            if (err !== null) {
                this.showErrorTimer = setTimeout(() => {
                    this.showError(null);
                }, 1500);
            } else if (this.showErrorTimer !== null) {
                clearTimeout(this.showErrorTimer);
                this.showErrorTimer = null;
            }
        }

        override async send(data: yup.InferType<typeof LoginSchema>) {
            await login((await api.users.login(data.login, data.password)).accessToken);
        }

        destroy() {
            if (this.showErrorTimer !== null) {
                clearTimeout(this.showErrorTimer);
            }
        }
    }

    const formState = new LoginFormState();
</script>

{#snippet renderTitle()}
    {#if formState.error}
        {formState.error}
    {:else}
        Login to {brand.plain}
    {/if}
{/snippet}

<Form
    novalidate
    onsubmit={async (e: SubmitEvent) => {
        await formState.submit(e);
    }}
>
    <FullscreenPage
        title={{ children: renderTitle, variant: formState.hasErrors ? 'danger' : undefined }}
        buttons={[{ children: 'Sign in', action: 'submit' }]}
    >
        <FormGroup class="mb-3">
            <Label class="fs-5">Username</Label>
            <Input
                name="login"
                bind:value={formState.data.login}
                feedback={formState.validationErrors.login}
                invalid={!!formState.validationErrors.login}
                disabled={formState.isLoading}
            />
        </FormGroup>

        <FormGroup class="mb-3">
            <Label class="fs-5">Password</Label>
            <Input
                type="password"
                name="password"
                bind:value={formState.data.password}
                feedback={formState.validationErrors.password}
                invalid={!!formState.validationErrors.password}
                disabled={formState.isLoading}
            />
        </FormGroup>
    </FullscreenPage>
</Form>
