// Bottleneko.Client/src/features/scripts/JsScriptEditor.tsx
﻿import { Editor, OnMount, Monaco } from '@monaco-editor/react';
import { editor } from 'monaco-editor';
import { useRef } from 'react';
import { Card } from 'react-bootstrap';
import { ScriptCode } from '../api/dtos.gen';
import typeDefs from './api/typeDefs';

export default function JsScriptEditor({ initialCode, onChange, props, className }: { initialCode?: string; onChange: (code: ScriptCode) => void; props?: object; className?: string }) {
    const editorRef = useRef<editor.IStandaloneCodeEditor | null>(null);

    const onEditorWillMount = (monaco: Monaco) => {
        monaco.languages.typescript.javascriptDefaults.setDiagnosticsOptions({
            noSemanticValidation: true,
            noSyntaxValidation: false,
        });

        monaco.languages.typescript.javascriptDefaults.setCompilerOptions({
            target: monaco.languages.typescript.ScriptTarget.Latest,
            lib: ['esnext'],
            allowNonTsExtensions: true,
            module: monaco.languages.typescript.ModuleKind.ESNext,
            moduleResolution: monaco.languages.typescript.ModuleResolutionKind.NodeJs,
            typeRoots: ['file:///node_modules/@types'],
        });

        const fixName = (path: string, name: string) => {
            name = name.substring(0, name.length - '.d.ts'.length);
            if (name === 'index') {
                return path;
            }
            else if (name.endsWith('/index')) {
                return path + '/' + name.substring(0, name.length - '/index'.length);
            }
            else {
                return path + '/' + name;
            }
        };

        const libs: Parameters<typeof monaco.languages.typescript.javascriptDefaults.setExtraLibs>[0] = [];

        for (const typeDef of typeDefs) {
            if (typeDef.path === 'bottleneko.gen.d.ts') {
                libs.push({ content: typeDef.src });
            }
            else {
                const packageName = fixName('neko', typeDef.path);
                const src = `declare module '${packageName}' {\n${typeDef.src}\n}\n`;
                libs.push({ content: src, filePath: 'file:///node_modules/@types/neko/' + typeDef.path });
            }
        }

        const packages = typeDefs
            .filter(typeDef => typeDef.path !== 'bottleneko.gen.d.ts')
            .map(typeDef => fixName('neko', typeDef.path))
            .map(name => `    "${name}": "*"`)
            .join(',\n');
        const packageJson = `{\n  "dependencies": {\n${packages}\n  }\n}`;
        libs.push({ content: packageJson, filePath: 'file:///package.json' });

        monaco.languages.typescript.javascriptDefaults.setExtraLibs(libs);
    };

    const onEditorMount: OnMount = (editor) => {
        editorRef.current = editor;
    };

    return (
        <Card className="flex-grow-1">
            <Card.Body style={{ minHeight: '20rem' }}>
                <Editor
                    defaultLanguage="javascript"
                    defaultValue={initialCode}
                    defaultPath="file:///script.js"
                    onMount={onEditorMount}
                    beforeMount={onEditorWillMount}
                    onChange={(code) => { onChange({ $type: 'JavaScript', source: code ?? '' }); }}
                    className={className ?? ''}
                    theme="vs-dark"
                    options={{ minimap: { enabled: false }, scrollbar: { vertical: 'visible', horizontal: 'auto' } }}
                    {...props}
                />
            </Card.Body>
        </Card>
    );
}

// src/Bottleneko.Client/src/lib/features/scripts/js/JsScriptEditor.svelte
<script lang="ts">
    import { Card, CardBody } from '@sveltestrap/sveltestrap';
    import { onDestroy, onMount } from 'svelte';
    import type { editor as MonacoEditor, IDisposable } from 'monaco-editor';
    import { getBindings, type Props } from './JsScriptEditor';
    import LoadingBanner from '$lib/components/LoadingBanner.svelte';

    const props: Props = $props();

    let destroyed = false;
    let editorElement: HTMLElement | undefined = $state();
    let editor: MonacoEditor.IStandaloneCodeEditor | null = $state(null);
    let subscription: IDisposable | null = $state(null);

    onMount(async () => {
        const bindings = await getBindings();
        const monaco = await import('monaco-editor');

        if (destroyed) {
            return;
        }

        monaco.typescript.typescriptDefaults.setDiagnosticsOptions({
            noSemanticValidation: false,
            noSyntaxValidation: false,
        });

        monaco.typescript.typescriptDefaults.setCompilerOptions({
            target: monaco.typescript.ScriptTarget.ESNext,
            lib: ['esnext'],
            allowNonTsExtensions: true,
            module: monaco.typescript.ModuleKind.ESNext,
            moduleResolution: monaco.typescript.ModuleResolutionKind.NodeJs,
            typeRoots: ['file:///node_modules/@types'],
        });

        const libs: Parameters<typeof monaco.typescript.typescriptDefaults.setExtraLibs>[0] = [];

        for (const [name, content] of bindings) {
            libs.push({ filePath: `file:///node_modules/${name}`, content });
        }

        const packageJson = {
            dependencies: {
                neko: '*',
            },
        };
        libs.push({ content: JSON.stringify(packageJson), filePath: 'file:///package.json' });

        monaco.typescript.typescriptDefaults.setExtraLibs(libs);

        if (editorElement) {
            const path = monaco.Uri.parse('file:///script.ts');
            const model =
                monaco.editor.getModel(path) ?? monaco.editor.createModel(props.initialCode ?? '', 'typescript', path);
            model.setValue(props.initialCode ?? '');

            editor = monaco.editor.create(editorElement, {
                model,
                theme: 'vs-dark',
                minimap: { enabled: false },
                scrollbar: { vertical: 'visible', horizontal: 'auto' },
            });
            subscription = editor.onDidChangeModelContent(() => {
                const code = editor?.getValue();
                if (code !== undefined) {
                    props.onchange?.({ $type: 'JavaScript', source: code });
                }
            });
        }
    });

    onDestroy(() => {
        destroyed = true;
        subscription?.dispose();
        subscription = null;
        editor?.dispose();
        editor = null;
    });
</script>

<Card class="flex-grow-1">
    <CardBody style="min-height: 20rem">
        <section style="display: flex; position: relative; text-align: initial; width: 100%; height: 100%;">
            <div style="width: 100%" bind:this={editorElement}>
                {#if editor === null}
                    <LoadingBanner size="xl" description="Loading code editor..." />
                {/if}
            </div>
        </section>
    </CardBody>
</Card>
