// Bottleneko.Client/src/features/connections/add-wizard/AddConnectionTest.tsx
import { Alert } from 'react-bootstrap';
import { useCallback, useState } from 'react';
import Highlight from 'react-highlight';
import { ConnectionDefinition } from '..';
import api from '../../api';
import { useAsync, useOnce } from '../../../app/hooks';
import { WizardNavigation } from '../../../components/WizardNavigation';
import { ErrorMetadata, extractErrorInfo } from '../../../app/utils';
import { Protocol } from '../../api/dtos.gen';
import { AddConnectionStage } from './AddConnectionView';

export default function AddConnectionTest({ definition, setStage }: { protocol: Protocol; definition: ConnectionDefinition; setStage: (stage: AddConnectionStage) => void }) {
    const [extra, setExtra] = useState<object | null>();
    const [error, setError] = useState<ErrorMetadata | null>();

    const onError = useCallback((err: unknown) => {
        setError(extractErrorInfo(err));
    }, []);

    const [testConfig, isLoading] = useAsync(useCallback(async () => {
        setExtra((await api.connections.test(definition.config)).extra);
    }, [definition.config]));

    useOnce(() => {
        void testConfig().catch(onError);
    });

    return (
        <>
            {
                isLoading
                    ? (
                            <Alert variant="primary">
                                <span className="fs-4">Testing configuration...</span>
                            </Alert>
                        )
                    : <></>
            }
            {
                !isLoading && error
                    ? (
                            <Alert variant="danger">
                                <p className="fs-4">Configuration test failed</p>

                                <Highlight className="json">{JSON.stringify(error, null, 2)}</Highlight>
                            </Alert>
                        )
                    : <></>
            }
            {
                !isLoading && !error
                    ? (
                            <Alert variant="success">
                                <span className="fs-4">Success! The configuration appears to be valid.</span>
                                {
                                    extra
                                        ? (
                                                <>
                                                    <p>Here&apos;s some additional information that might be helpful to you:</p>
                                                    <Highlight className="json">{JSON.stringify(extra, null, 2)}</Highlight>
                                                </>
                                            )
                                        : <></>
                                }
                            </Alert>
                        )
                    : <></>
            }

            <WizardNavigation
                back={isLoading
                    ? undefined
                    : () => { setStage({ stage: 'config', definition }); }}
                next={!isLoading && !error
                    ? () => { setStage({ stage: 'finish', definition }); }
                    : undefined}
            />
        </>
    );
}

// Bottleneko.Client/src/routes/connections/add/[protocol]/AddConnectionTest.svelte
<script lang="ts">
    import WizardNavigation from '$lib/components/WizardNavigation.svelte';
    import { Connections } from '$lib/features/connections';
    import { getAbortSignal, onMount } from 'svelte';
    import { extractErrorInfo, type ErrorMetadata } from '$lib';
    import { Alert } from '@sveltestrap/sveltestrap';
    import Highlight from 'svelte-highlight';
    import json from 'svelte-highlight/languages/json';
    import { goto } from '$app/navigation';
    import { resolve } from '$app/paths';
    import type { Props } from './AddConnectionTest';

    const props: Props = $props();
    let extra: object | null = $state(null);
    let error: ErrorMetadata | null = $state(null);
    let isLoading = $state(true);

    onMount(async () => {
        if (!Connections.provider) {
            await goto(resolve('/'));
            return;
        }

        try {
            extra = await Connections.provider.test(props.definition.config, { signal: getAbortSignal() });
        } catch (err: unknown) {
            error = extractErrorInfo(err);
        } finally {
            isLoading = false;
        }
    });
</script>

<div>
    {#if isLoading}
        <Alert color="primary" class="w-100">
            <span class="fs-4">Testing configuration...</span>
        </Alert>
    {:else if error}
        <Alert color="danger" class="w-100">
            <p class="fs-4">Configuration test failed</p>

            <Highlight language={json} code={JSON.stringify(error, null, 2)} />
        </Alert>
    {:else}
        <Alert color="success" class="w-100">
            <span class="fs-4">Success! The configuration appears to be valid.</span>
            {#if extra}
                <p>Here&apos;s some additional information that might be helpful to you:</p>
                <Highlight language={json} code={JSON.stringify(extra, null, 2)} />
            {/if}
        </Alert>
    {/if}
    <WizardNavigation
        back={() => {
            props.onstagechange?.({ id: 'config', protocol: props.protocol, definition: props.definition });
        }}
        next={!isLoading && !error
            ? () => {
                  props.onstagechange?.({ id: 'finish', protocol: props.protocol, definition: props.definition });
              }
            : undefined}
    />
</div>
