// Bottleneko.Client/src/features/log/LogViewer.tsx
﻿import './LogViewer.scss';
import { ToggleButton, ButtonGroup } from 'react-bootstrap';
import { useCallback, useState } from 'react';
import dateFormat from 'dateformat';
import { useSubscription } from '../websockets/hooks';
import { LogLetter, LogSeverity, LogSourceType } from '../api/dtos.gen';
import { TableColumn } from '../../components/table';
import ScrollableTable from '../../components/table/ScrollableTable';
import LogSourceDisplay from './LogSourceDisplay';

type LogSeverityFilter = Record<LogSeverity, boolean>;

export default function LogViewer({ sourceType, sourceId, className }: { sourceType?: LogSourceType; sourceId?: string; className?: string }) {
    const [severityFilter, setSeverityFilter] = useState<LogSeverityFilter>({
        [LogSeverity.Critical]: true,
        [LogSeverity.Error]: true,
        [LogSeverity.Warning]: true,
        [LogSeverity.Info]: true,
        [LogSeverity.Verbose]: false,
        [LogSeverity.Debug]: false,
    });

    const { events } = useSubscription<LogLetter>({
        subscription: {
            type: 'Logs',
            filter: {
                severities: Object.keys(severityFilter).filter(severity => severityFilter[severity as LogSeverity]) as LogSeverity[],
                sourceType: sourceType ?? null,
                sourceId: sourceId ?? null,
                category: null,
            },
        },
        maxEvents: 500,
    });

    const toggleSeverityFilter = useCallback((severity: LogSeverity) => {
        const newSeverityFilter = { ...severityFilter, [severity]: !severityFilter[severity] };
        setSeverityFilter(newSeverityFilter);
    }, [severityFilter]);

    const getSeverityButtonVariant = (severity: LogSeverity) => {
        switch (severity) {
            case LogSeverity.Critical:
            case LogSeverity.Error:
            case LogSeverity.Warning:
            case LogSeverity.Info:
            case LogSeverity.Verbose:
            case LogSeverity.Debug:
                return 'dark';

            default:
                return 'dark';
        }
    };

    const showSource = sourceType !== LogSourceType.Connection && sourceType !== LogSourceType.Script;

    const columns: TableColumn[] = [];
    columns.push({ id: 'timestamp', header: 'Timestamp' });
    if (showSource) {
        columns.push({ id: 'source', header: 'Source' });
    }
    columns.push({ id: 'category', header: 'Category' });
    columns.push({ id: 'message', header: 'Message' });

    const renderRow = (message: LogLetter) => ({
        id: message.id,
        className: `log-message log-message-${message.severity.toLowerCase()} font-monospace`,
        columns: {
            timestamp: {
                className: 'log-message-timestamp',
                content: dateFormat(new Date(message.timestamp), 'yyyy-mm-dd HH:MM:ss'),
            },
            source: {
                className: 'log-message-source',
                content: <LogSourceDisplay sourceType={message.sourceType} sourceId={message.sourceId} />,
            },
            category: {
                className: 'log-message-category',
                content: message.category,
            },
            message: {
                className: 'log-message-text',
                content: message.text,
            },
        },
    });

    return (
        <div className="h-100" style={{ padding: '0.5em' }}>
            <ScrollableTable
                columns={columns}
                render={renderRow}
                data={events}
                placeholder={() => <em className="text-secondary fst-italic">(no messages)</em>}
                className={className}
                title="Log Messages"
                highlightHeader
            >
                <ScrollableTable.HeaderExtra position="end">
                    <ButtonGroup style={{ maxWidth: '1000px' }}>
                        {
                            Object.keys(severityFilter).map(severity => (
                                <ToggleButton
                                    key={severity}
                                    variant={`outline-${getSeverityButtonVariant(severity as LogSeverity)}`}
                                    type="checkbox"
                                    id={`log-severity-${severity}`}
                                    className={severityFilter[severity as LogSeverity] ? '' : 'text-white'}
                                    value={severity}
                                    checked={severityFilter[severity as LogSeverity]}
                                    onChange={(e) => { toggleSeverityFilter(e.currentTarget.value as LogSeverity); }}
                                    style={{}}
                                    size="sm"
                                >
                                    {severity}
                                </ToggleButton>
                            ))
                        }
                    </ButtonGroup>
                </ScrollableTable.HeaderExtra>
            </ScrollableTable>
        </div>
    );
}

// Bottleneko.Client/src/lib/features/log/LogViewer.svelte
<script lang="ts">
    import './styles.scss';
    import { type LogSeverity, type LogLetter } from '$lib/api/dtos.gen';
    import type { TypedRendererProps, TypedDataTable } from '$lib/components/DataTable';
    import DataTable from '$lib/components/DataTable.svelte';
    import { Subscriber } from '../ws/WebSocketConnection.svelte';
    import LogRowRenderer from './LogRowRenderer.svelte';
    import { Button, ButtonGroup } from '@sveltestrap/sveltestrap';
    import { getSeverityButtonVariant, type Props, type TableType } from './LogViewer';

    const props: Props = $props();

    let severityFilter: Record<LogSeverity, boolean> = $state({
        Critical: true,
        Error: true,
        Warning: true,
        Info: true,
        Verbose: false,
        Debug: false,
    });

    const toggleSeverityFilter = (severity: LogSeverity) => {
        severityFilter = { ...severityFilter, [severity]: !severityFilter[severity] };
    };

    const subscriber = new Subscriber<LogLetter>();
    $effect(() => {
        subscriber.subscribe({
            topic: {
                $type: 'Logs',
                filter: {
                    severities: (Object.keys(severityFilter) as LogSeverity[]).filter(
                        (severity) => severityFilter[severity],
                    ),
                    sourceType: props.sourceType ?? null,
                    sourceId: props.sourceId ?? null,
                    category: null,
                },
            },
        });
    });

    const columns = $derived({
        timestamp: { header: 'Timestamp' },
        source: props.sourceType !== 'Connection' && props.sourceType !== 'Script' ? { header: 'Source' } : undefined,
        category: { header: 'Category' },
        message: { header: 'Message' },
    });

    const LogViewerTable = DataTable as TypedDataTable<TableType>;
    const rendererProps: TypedRendererProps<TableType> = (props) => {
        return props;
    };
</script>

<div class="h-100">
    <LogViewerTable
        title="Log messages"
        class={props.class}
        highlight-header
        renderer={LogRowRenderer}
        {rendererProps}
        {columns}
        rows={subscriber.isLoading
            ? undefined
            : subscriber.mail.map((message) => ({
                  id: message.id,
                  class: `log-message log-message-${message.severity.toLowerCase()} font-monospace`,
                  cells: {
                      timestamp: {
                          class: 'log-message-timestamp',
                      },
                      source: {
                          class: 'log-message-source',
                      },
                      category: {
                          class: 'log-message-category',
                      },
                      message: {
                          class: 'log-message-text',
                      },
                  },
                  data: message,
              }))}
    >
        {#snippet placeholder()}
            <em class="text-secondary fst-italic">(no messages)</em>
        {/snippet}

        {#snippet endHeaderExtra()}
            <ButtonGroup style="max-width: 1000px">
                {#each Object.keys(severityFilter) as LogSeverity[] as severity (severity)}
                    <Button
                        color={getSeverityButtonVariant(severity, severityFilter[severity])}
                        class={severityFilter[severity] ? '' : 'text-white'}
                        onclick={() => {
                            toggleSeverityFilter(severity);
                        }}
                        size="sm"
                    >
                        {severity}
                    </Button>
                {/each}
            </ButtonGroup>
        {/snippet}
    </LogViewerTable>
</div>
