// Bottleneko.Client/src/lib/components/ConfirmationDialog.svelte
<script lang="ts">
    import { Button } from '@sveltestrap/sveltestrap';
    import ModalDialog from './ModalDialog.svelte';
    import type { Props } from './ConfirmationDialog';

    let isAccepting = $state(false);

    const {
        loading = false,
        acceptText = 'Accept',
        cancelText = 'Cancel',
        acceptVariant = 'primary',
        title = 'Confirmation',
        ...props
    }: Props = $props();

    const doAccept = async () => {
        isAccepting = true;
        try {
            await props.onaccept?.();
        } finally {
            isAccepting = false;
        }
    };
</script>

<ModalDialog {title} show={props.show} onclose={props.onclose} size="lg" children={props.children}>
    {#snippet footer()}
        <Button
            onclick={loading || isAccepting ? undefined : props.onclose}
            color="secondary"
            disabled={loading || isAccepting}>{cancelText}</Button
        >
        <Button
            onclick={loading || isAccepting ? undefined : doAccept}
            color={acceptVariant}
            disabled={loading || isAccepting}>{acceptText}</Button
        >
    {/snippet}
</ModalDialog>

// Bottleneko.Client/src/components/ConfirmationDialog.tsx
﻿import { ReactNode } from 'react';
import { ButtonVariant } from 'react-bootstrap/esm/types';
import ModalDialog from './modal-dialog/ModalDialog';

export interface ConfirmationDialogProps { children?: ReactNode; title?: string; show: boolean; onCancel?: () => void; onAccept?: () => void; cancelText?: string; acceptText?: string; acceptVariant?: ButtonVariant }

export default function ConfirmationDialog({ children, title, show, onCancel, onAccept, cancelText, acceptText, acceptVariant }: ConfirmationDialogProps) {
    return (
        <ModalDialog
            title={title ?? 'Confirmation'}
            show={show}
            onCancel={onCancel}
        >
            {children}

            <ModalDialog.Button onClick={onCancel} variant="secondary">{cancelText ?? 'Cancel'}</ModalDialog.Button>
            <ModalDialog.Button onClick={onAccept} variant={acceptVariant ?? 'primary'}>{acceptText ?? 'Accept'}</ModalDialog.Button>
        </ModalDialog>
    );
}
