// src/Bottleneko.Client/src/routes/SidePanel.svelte
<script lang="ts">
    import { page } from '$app/state';
    import { resolve } from '$app/paths';
    import { authState, logout } from '$lib/features/auth.svelte';
    import InlineIcon from '$lib/components/InlineIcon.svelte';
    import { brand } from '$lib/props';
    import {
        Dropdown,
        DropdownItem,
        DropdownMenu,
        DropdownToggle,
        Nav,
        NavItem,
        NavLink,
        Spinner,
    } from '@sveltestrap/sveltestrap';
    import { Connections } from '$lib/features/connections';
    import ProtocolIcon from '$lib/features/connections/ProtocolIcon.svelte';
    import ConnectionStatusIcon from '$lib/features/connections/ConnectionStatusIcon.svelte';
    import IconButton from '$lib/components/IconButton.svelte';
    import { LocalConnection } from '$lib/features/connections/provider.svelte';

    const match = (
        route: ReturnType<typeof resolve> | ReturnType<typeof resolve>[],
        options?: { exact?: boolean; filter?: (params: typeof page.params) => boolean },
    ): boolean => {
        const opt = {
            exact: false,
            filter: () => true,
            ...options,
        };

        if (page.route.id === null) {
            return false;
        }

        if (typeof route === 'string') {
            return (
                (page.route.id === route ||
                    (!opt.exact && page.route.id.startsWith(route.endsWith('/') ? route : route + '/'))) &&
                opt.filter(page.params)
            );
        } else {
            return route.reduce((prev, cur) => prev || match(cur, opt), false);
        }
    };

    $effect(() => {
        void page.url;
        document.querySelector('body')?.classList.remove('sidebar-shown');
    });
</script>

{#snippet button(
    text: string,
    dest: Extract<Parameters<typeof match>[0], string>,
    icon: string | null,
    matches?: { routes?: Parameters<typeof match>[0]; options?: Parameters<typeof match>[1] },
)}
    {@const isMatch = match(matches?.routes === undefined ? dest : matches.routes, matches?.options)}
    <NavItem>
        <NavLink href={dest} active={isMatch} class="text-white fs-5 fw-bold">
            {#if icon !== null}
                <span class="me-1"><InlineIcon {icon} /></span>
            {/if}
            {text}
        </NavLink>
    </NavItem>
{/snippet}

{#snippet buttonWithAdd(
    text: string,
    dest: Extract<Parameters<typeof match>[0], string>,
    addDest: string,
    addTooltip: string,
    icon: string | null,
    matches?: { routes?: Parameters<typeof match>[0]; options?: Parameters<typeof match>[1] },
)}
    {@const isMatch = match(
        matches?.routes === undefined
            ? [dest, addDest as Extract<Parameters<typeof match>[0], string>]
            : matches.routes,
        matches?.options,
    )}
    <NavItem>
        <NavLink href={dest} active={isMatch} class="d-flex">
            <span class="flex-grow-1 text-white fs-5 fw-bold">
                {#if icon !== null}
                    <span class="me-1"><InlineIcon {icon} /></span>
                {/if}
                {text}
            </span>

            <IconButton href={addDest} icon="plus-lg" tooltip={addTooltip} variant={isMatch ? 'light' : 'primary'} />
        </NavLink>
    </NavItem>
{/snippet}

{#snippet connectionButton(connection: LocalConnection)}
    {@const isMatch = match('/connections/[connectionId]', {
        filter: (params) => params.connectionId === connection.data.id,
    })}
    <NavItem class="w-100">
        <NavLink
            href={resolve('/connections/[connectionId]', { connectionId: connection.data.id })}
            active={isMatch}
            class="text-white fs-6"
        >
            <div class="d-flex align-items-center" style:gap="1rem">
                <div class="flex-shrink-0 mt-0">
                    <ProtocolIcon protocol={connection.data.protocol} size="2em" />
                </div>
                <span class="flex-grow-1 text-collapse">{connection.data.name}</span>
                <div class="flex-shrink-0">
                    <ConnectionStatusIcon status={connection.data.extendedStatus} />
                </div>
            </div>
        </NavLink>
    </NavItem>
{/snippet}

<aside class="d-flex flex-column p-3 shadow" style:background-color="#171717">
    <a href={resolve('/')} class="text-white text-decoration-none brand">
        <span style:font-size="2rem" style:font-weight="bold">
            {#each brand.formatted as element (element)}
                <span class:brand-highlight={element.highlighted}>{element.text}</span>
            {/each}
        </span>

        <div class="sidebar-button float-end">
            <IconButton
                icon="list"
                tooltip={null}
                variant="outline-secondary"
                style="width: 3em; height: 3em"
                onclick={(e: MouseEvent) => {
                    document.querySelector('body')?.classList.toggle('sidebar-shown');
                    e.preventDefault();
                }}
            />
        </div>
    </a>

    <hr />

    <Nav pills class="d-flex flex-column">
        <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression -->
        {@render button('Dashboard', resolve('/'), 'collection', { options: { exact: true } })}
        <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression -->
        {@render button('Messages', resolve('/messages'), 'chat-left-text')}
        <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression -->
        {@render buttonWithAdd(
            'Connections',
            resolve('/connections'),
            resolve('/connections/add'),
            'Add a new connection',
            'wifi',
            {
                options: { exact: true },
            },
        )}
        <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression -->
        {@render buttonWithAdd(
            'Scripting',
            resolve('/scripts'),
            resolve('/scripts/add'),
            'Create a new script',
            'braces',
            {
                options: { exact: true },
            },
        )}
        <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression -->
        {@render button('Settings', resolve('/settings'), 'tools')}
    </Nav>

    <Nav pills class="d-flex mt-auto">
        {#if Connections.provider?.list}
            {#each Connections.provider.list as connection (connection.data.id)}
                <!-- eslint-disable-next-line @typescript-eslint/no-confusing-void-expression -->
                {@render connectionButton(connection)}
            {/each}
        {:else}
            <Spinner type="border" class="my-4 mx-auto" />
        {/if}
    </Nav>

    <hr />

    <Dropdown>
        <DropdownToggle tag="span" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle">
            <span class="menu-toggle">Logged in as <strong>{authState.data.me?.displayName ?? '?'}</strong></span>
        </DropdownToggle>

        <DropdownMenu color="dark" class="shadow">
            <DropdownItem onclick={logout}>
                <InlineIcon icon="person" />
                <span style:margin-left="0.5em">Sign out</span>
            </DropdownItem>
        </DropdownMenu>
    </Dropdown>
</aside>

<style lang="scss">
    @import '../vars.scss';

    .brand {
        span {
            display: block;
            float: left;
        }

        .brand-highlight {
            color: $primary;
            transform: translateY(0.1em);
        }
    }

    .menu-toggle {
        user-select: none;
        cursor: pointer;
    }

    aside {
        position: fixed;
        top: 0;
        left: 0;
        width: 25rem;
        height: 100dvh;
        overflow-y: auto;
    }

    @media only screen and (max-width: $small-screen-width) {
        aside {
            width: max(20rem, 20vw);
        }
    }

    @media only screen and (max-width: $mobile-view-width) {
        aside {
            width: 100dvw;
            height: 5rem;
            z-index: 100;
            overflow-y: hidden;
            overscroll-behavior-y: contain;
        }
    }
</style>

// Bottleneko.Client/src/components/SidePanel.tsx
import { LinkContainer } from 'react-router-bootstrap';
import { Dropdown, Nav, Spinner } from 'react-bootstrap';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { CSSProperties, useEffect, useRef } from 'react';
import ProtocolIcon from '../features/connections/ProtocolIcon';
import ConnectionStatusIcon from '../features/connections/ConnectionStatusIcon';
import { useAuth } from '../features/auth/context';
import { useConnections } from '../features/connections/context';
import { branding } from '../props';
import IconButton from './IconButton';
import InlineIcon from './InlineIcon';

// Nav links getting stuck active: https://github.com/react-bootstrap/react-router-bootstrap/issues/242

export default function SidePanel({ className = '', style = {}, props }: { className?: string; style?: CSSProperties; props?: object }) {
    const auth = useAuth();
    const connections = useConnections();
    const location = useLocation();
    const navigate = useNavigate();
    const sideBarRef = useRef<HTMLElement>(null);

    useEffect(() => {
        document.querySelector('body')?.classList.remove('sidebar-shown');
        sideBarRef.current?.scrollTo({ top: 0, left: 0 });
    }, [location]);

    return (
        <aside className={`d-flex flex-column p-3 shadow ${className}`} style={{ backgroundColor: '#111', ...style }} ref={sideBarRef} {...props}>
            <Link to="/" className="text-white text-decoration-none branding">
                <span style={{ fontSize: '2rem', fontWeight: 'bold' }}>
                    {
                        branding.formatted.map((element, idx) => (
                            <span key={`part-${idx.toString()}`} className={element.highlighted ? 'branding-highlight' : ''}>{element.text}</span>
                        ))
                    }
                </span>
                <IconButton
                    icon="list"
                    variant="outline-secondary"
                    tooltip={null}
                    className="sidebar-button float-end"
                    style={{ width: '3em', height: '3em' }}
                    onClick={(e) => {
                        document.querySelector('body')?.classList.toggle('sidebar-shown');
                        e.preventDefault();
                    }}
                />
            </Link>

            <hr />

            <Nav variant="pills" className="d-flex flex-column">
                <Nav.Item key="home">
                    <LinkContainer to="/"><Nav.Link active={false} className="text-white fs-5 fw-bold">Dashboard</Nav.Link></LinkContainer>
                </Nav.Item>

                <Nav.Item key="messages">
                    <LinkContainer to="/messages"><Nav.Link active={false} className="text-white fs-5 fw-bold">Messages</Nav.Link></LinkContainer>
                </Nav.Item>

                <Nav.Item key="connections">
                    <LinkContainer to="/connections">
                        <Nav.Link active={location.pathname === '/connections/add'} className="d-flex">
                            <span className="flex-grow-1 text-white fs-5 fw-bold">Connections</span>

                            <IconButton
                                icon="plus-lg"
                                tooltip="Add a new connection"
                                variant={(location.pathname === '/connections' || location.pathname === '/connections/add') ? 'light' : 'primary'}
                                size="sm"
                                onClick={(e) => {
                                    e.preventDefault();
                                    e.stopPropagation();
                                    navigate('/connections/add');
                                }}
                            />
                        </Nav.Link>
                    </LinkContainer>
                </Nav.Item>

                <Nav.Item key="scripts">
                    <LinkContainer to="/scripts">
                        <Nav.Link active={location.pathname === '/scripts' || location.pathname.startsWith('/scripts/')} className="d-flex">
                            <span className="flex-grow-1 text-white fs-5 fw-bold">Scripting</span>

                            <IconButton
                                icon="plus-lg"
                                tooltip="Create a new script"
                                variant={(location.pathname === '/scripts' || location.pathname.startsWith('/scripts/')) ? 'light' : 'primary'}
                                size="sm"
                                onClick={(e) => {
                                    e.preventDefault();
                                    e.stopPropagation();
                                    navigate('/scripts/add');
                                }}
                            />
                        </Nav.Link>
                    </LinkContainer>
                </Nav.Item>

                <Nav.Item key="users">
                    <LinkContainer to="/users">
                        <Nav.Link active={location.pathname === '/users' || location.pathname.startsWith('/users/')} className="d-flex">
                            <span className="flex-grow-1 text-white fs-5 fw-bold">Users</span>

                            <IconButton
                                icon="plus-lg"
                                tooltip="Add a new user"
                                variant={(location.pathname === '/users' || location.pathname.startsWith('/users/')) ? 'light' : 'primary'}
                                size="sm"
                                onClick={(e) => {
                                    e.preventDefault();
                                    e.stopPropagation();
                                    navigate('/users/add');
                                }}
                            />
                        </Nav.Link>
                    </LinkContainer>
                </Nav.Item>

                <Nav.Item key="settings">
                    <LinkContainer to="/settings"><Nav.Link active={false} className="text-white fs-5 fw-bold">Settings</Nav.Link></LinkContainer>
                </Nav.Item>
            </Nav>

            <Nav variant="pills" className="d-flex mt-auto">
                {
                    !connections?.state.list
                        ? <Spinner animation="border" className="my-4 mx-auto" />
                        : connections.state.list.map(c => (
                                <Nav.Item key={`connection-${c.data.id}`} className="w-100">
                                    <LinkContainer to={`/connections/${c.data.id}`}>
                                        <Nav.Link active={false} className="text-white fs-6">
                                            <div className="d-flex align-items-center" style={{ gap: '1rem' }}>
                                                <ProtocolIcon protocol={c.data.protocol} size="2em" className="flex-shrink-0 mt-0" />
                                                <span className="flex-grow-1 text-collapse">{c.data.name}</span>
                                                <div className="flex-shrink-0"><ConnectionStatusIcon status={c.data.extendedStatus} /></div>
                                            </div>
                                        </Nav.Link>
                                    </LinkContainer>
                                </Nav.Item>
                            ))
                }
            </Nav>

            <hr />

            <Dropdown>
                <Dropdown.Toggle as="a" href="#" className="d-flex align-items-center text-white text-decoration-none">
                    <span>
                        Logged in as
                        {' '}
                        <strong>{auth?.state.me?.displayName ?? '?'}</strong>
                    </span>
                </Dropdown.Toggle>

                <Dropdown.Menu variant="dark" className="shadow">
                    <LinkContainer to={`/users/${auth?.state.me?.id ?? ''}`}>
                        <Dropdown.Item>
                            <InlineIcon icon="person-lines-fill" style={{ marginRight: '0.5em' }} />
                            Profile
                        </Dropdown.Item>
                    </LinkContainer>
                    <Dropdown.Item onClick={() => { auth?.actions.logout(); }}>
                        <InlineIcon icon="person" style={{ marginRight: '0.5em' }} />
                        Sign out
                    </Dropdown.Item>
                </Dropdown.Menu>
            </Dropdown>
        </aside>
    );
}
