// Bottleneko.Client/src/features/connections/twitch/TwitchConfigEditor.tsx
import { Alert, Button, Card, Form, InputGroup } from 'react-bootstrap';
import { Formik } from 'formik';
import { forwardRef, useState } from 'react';
import * as yup from 'yup';
import { ConnectionDefinition } from '..';
import { TwitchProtocolChannel } from '../../api/dtos.gen';
import IconButton from '../../../components/IconButton';
import { useProxies } from '../../proxies/context';
import TwitchChannelEditor from './TwitchChannelEditor';
import TwitchAuthWizard from './TwitchAuthWizard';
import { scopeToScopeName } from './scopes';
import { topicsInfo } from './topics';
import { TwitchConfigSchema, TwitchProtocolChannelSchema } from '.';

const MAX_SUBS = 300;
const MAX_COST = 10;

const countSubs = (channels: TwitchProtocolChannel[]) => channels.reduce((prev, cur) => prev + cur.eventSubscriptions.length, 0);
const countCost = (me: string, channels: TwitchProtocolChannel[]) => channels.reduce((prev, cur) => prev + (cur.name.toLowerCase() === me.toLowerCase() ? 0 : cur.eventSubscriptions.map(s => topicsInfo.get(s)?.cost ?? 0).reduce((prev, cur) => prev + cur)), 0);

const schema = yup.object().shape({
    name: yup.string().default('').required('Name should not be empty'),
    config: TwitchConfigSchema.required(),
});

const defaultDefinition = schema.getDefault();
type TwitchConnectionDefinition = yup.InferType<typeof schema>;

const TwitchConfigEditor = forwardRef(({ definition, onValidated, disabled = false }: { definition: ConnectionDefinition | null; disabled?: boolean; onValidated: (definition: ConnectionDefinition) => void }, ref: React.ForwardedRef<HTMLFormElement>) => {
    const proxies = useProxies();
    const [isAuthShown, setIsAuthShown] = useState(false);
    const [editedChannel, setEditedChannel] = useState<TwitchProtocolChannel | null>(null);

    return (
        <>

            <Formik validationSchema={schema} onSubmit={onValidated} initialValues={definition as (TwitchConnectionDefinition | null) ?? defaultDefinition} validateOnChange={false}>
                {({ handleSubmit, handleChange, setFieldValue, values, errors }) => (
                    <>
                        <TwitchAuthWizard
                            show={isAuthShown}
                            onSuccess={(auth) => {
                                const oldChannel = values.config.auth.me;
                                void setFieldValue('config.auth', auth);
                                if (oldChannel !== auth.me) {
                                    void setFieldValue('config.channels', [{ ...TwitchProtocolChannelSchema.getDefault(), name: auth.me }]);
                                }
                                setIsAuthShown(false);
                            }}
                            onCancel={() => { setIsAuthShown(false); }}
                        />

                        <TwitchChannelEditor
                            show={!!editedChannel}
                            channel={editedChannel ?? undefined}
                            isMine={editedChannel?.name.toLowerCase() === values.config.auth.me.toLowerCase()}
                            onSuccess={(newChannel) => {
                                const newChannels: (TwitchProtocolChannel | null)[] = [...values.config.channels];
                                let found = false;
                                for (let i = 0; i < newChannels.length; i++) {
                                    if (newChannels[i]?.name === newChannel.name) {
                                        newChannels[i] = null;
                                    }

                                    if (newChannels[i]?.name === editedChannel?.name) {
                                        newChannels[i] = newChannel;
                                        found = true;
                                    }
                                }
                                if (!found) {
                                    newChannels.push(newChannel);
                                }
                                void setFieldValue('config.channels', newChannels.filter(channel => !!channel));
                                setEditedChannel(null);
                            }}
                            onCancel={() => { setEditedChannel(null); }}
                        />

                        <Form
                            noValidate
                            onSubmit={(e) => {
                                e.preventDefault();
                                e.stopPropagation();
                                handleSubmit();
                            }}
                            ref={ref}
                            className="d-flex flex-column"
                            style={{ gap: '1rem' }}
                        >
                            <Form.Group>
                                <Form.Label>Name</Form.Label>
                                <Form.Control name="name" value={values.name} onChange={handleChange} isInvalid={!!errors.name} disabled={disabled} autoComplete="off" />
                                <Form.Text muted>
                                    Name is an identifier for the connection. It can be anything as long as it is informative for you.
                                </Form.Text>
                                <Form.Control.Feedback type="invalid">
                                    {errors.name}
                                </Form.Control.Feedback>
                            </Form.Group>

                            <div className="d-flex flex-column align-items-center" style={{ gap: '1rem' }}>
                                <Button size="lg" onClick={() => { setIsAuthShown(true); }} variant="primary" style={{ width: 'calc(min(100%, 40rem))' }}>
                                    Connect Twitch account
                                </Button>

                                <Alert variant={values.config.auth.me ? 'success' : 'warning'} style={{ width: 'calc(min(100%, 40rem))' }}>
                                    <p className="fs-4 text-center my-0">
                                        {
                                            values.config.auth.me
                                                ? (
                                                        <>
                                                            Logged in as
                                                            {' '}
                                                            <strong>{values.config.auth.me}</strong>
                                                        </>
                                                    )
                                                : 'Not logged in'
                                        }
                                    </p>
                                </Alert>
                            </div>

                            {
                                values.config.auth.me
                                    ? (
                                            <Card>
                                                <Card.Header>Granted API scopes</Card.Header>
                                                <Card.Body>
                                                    <span className="font-monospace">{values.config.auth.scopes.map(scope => scopeToScopeName.get(scope)).join(', ')}</span>
                                                </Card.Body>
                                                <Card.Footer><a href="https://dev.twitch.tv/docs/authentication/scopes/" target="_blank" rel="noreferrer">Documentation</a></Card.Footer>
                                            </Card>
                                        )
                                    : <></>
                            }

                            <Form.Group>
                                <Form.Switch name="config.receiveEvents" label="Receive channel events" checked={values.config.receiveEvents} onChange={handleChange} isInvalid={!!errors.config?.receiveEvents} disabled={disabled || !values.config.auth.me} />
                                <Form.Text muted>
                                    If this option is enabled, in addition to allowing the bot to access the Twitch API, it will also keep an active connection to Twitch and receive new channel events.
                                </Form.Text>
                                <Form.Control.Feedback type="invalid">
                                    {errors.config?.receiveEvents}
                                </Form.Control.Feedback>
                            </Form.Group>

                            {
                                values.config.receiveEvents && values.config.auth.me
                                    ? (
                                            <>
                                                <Form.Group>
                                                    <Form.Label>Channels</Form.Label>
                                                    <div>
                                                        {
                                                            values.config.channels.map((channel, idx) => (
                                                                <InputGroup key={`channel-${idx.toString()}`} className="float-start me-2 mb-2" style={{ width: '15rem' }}>
                                                                    <Form.Control
                                                                        name={`channel-${idx.toString()}`}
                                                                        value={channel.name}
                                                                        readOnly={true}
                                                                    />
                                                                    <IconButton
                                                                        icon="gear-fill"
                                                                        tooltip="Edit properties"
                                                                        style={{ width: '2.5em', height: '2.5em', padding: '0.5em' }}
                                                                        variant="outline-success"
                                                                        onClick={() => { setEditedChannel(channel); }}
                                                                        disabled={disabled || !values.config.auth.me}
                                                                    />
                                                                    <IconButton
                                                                        icon="trash3-fill"
                                                                        tooltip="Delete channel"
                                                                        style={{ width: '2.5em', height: '2.5em', padding: '0.5em' }}
                                                                        variant="outline-danger"
                                                                        onClick={() => {
                                                                            const channels = [...values.config.channels];
                                                                            channels.splice(idx, 1);
                                                                            void setFieldValue('config.channels', channels);
                                                                        }}
                                                                        disabled={disabled || !values.config.auth.me || values.config.auth.me.toLowerCase() === channel.name.toLowerCase()}
                                                                    />
                                                                </InputGroup>
                                                            ))
                                                        }

                                                        <IconButton
                                                            icon="plus-lg"
                                                            tooltip="Add channel"
                                                            style={{ height: '2.5em' }}
                                                            variant="primary"
                                                            onClick={() => { setEditedChannel(TwitchProtocolChannelSchema.getDefault()); }}
                                                            disabled={disabled || !values.config.auth.me || values.config.channels.length >= 100}
                                                        >
                                                        </IconButton>
                                                    </div>
                                                </Form.Group>

                                                <Alert variant={countSubs(values.config.channels) <= MAX_SUBS && countCost(values.config.auth.me, values.config.channels) <= MAX_COST ? 'success' : 'danger'}>
                                                    <p className="fs-4 mb-2">
                                                        Limits
                                                    </p>
                                                    Twitch has strict limits on the amount of events bots can subscribe to at once. The current known limits are:
                                                    <br />
                                                    <strong>
                                                        {countSubs(values.config.channels)}
                                                        {' '}
                                                        /
                                                        {' '}
                                                        {MAX_SUBS}
                                                    </strong>
                                                    {' '}
                                                    total subscriptions
                                                    <br />
                                                    <strong>
                                                        {countCost(values.config.auth.me, values.config.channels)}
                                                        {' '}
                                                        /
                                                        {' '}
                                                        {MAX_COST}
                                                    </strong>
                                                    {' '}
                                                    total cost
                                                    <p className="mt-2 mb-0">
                                                        These limits are subject to change and are partially undocumented. Subscribing to a large number topics can also negatively affect startup times, so it is recommended to only subscribe to topics that are absolutely necessary.
                                                    </p>
                                                </Alert>
                                            </>
                                        )
                                    : <></>
                            }

                            <Form.Group>
                                <Form.Label>Proxy</Form.Label>
                                <Form.Select name="config.proxyId" value={values.config.proxyId} onChange={handleChange} isInvalid={!!errors.config?.proxyId} disabled={disabled}>
                                    <option value="">Don&apos;t use a proxy</option>
                                    {
                                        proxies?.state.list?.map(proxy => (
                                            <option key={proxy.data.id} value={proxy.data.id}>{proxy.data.name}</option>
                                        ))
                                    }
                                </Form.Select>
                                <Form.Text muted>
                                    Use a proxy server for outgoing connections.
                                </Form.Text>
                                <Form.Control.Feedback type="invalid">
                                    {errors.config?.proxyId}
                                </Form.Control.Feedback>
                            </Form.Group>
                        </Form>
                    </>
                )}
            </Formik>
        </>
    );
});

TwitchConfigEditor.displayName = 'TwitchConfigEditor';

export default TwitchConfigEditor;

// Bottleneko.Client/src/lib/features/connections/protocols/TwitchConfigEditor.svelte
<script lang="ts">
    import {
        Alert,
        Button,
        Card,
        CardBody,
        CardFooter,
        CardHeader,
        Form,
        FormFeedback,
        FormGroup,
        FormText,
        Input,
        InputGroup,
        Label,
    } from '@sveltestrap/sveltestrap';
    import type { Props, ConnectionDefinition } from '..';
    import { FormState } from '$lib/FormState.svelte';
    import { Proxies } from '$lib/features/proxies';
    import type { TwitchAuth, TwitchProtocolChannel, TwitchProtocolConfiguration } from '$lib/api/dtos.gen';
    import {
        countCost,
        countSubs,
        FormSchema,
        MAX_COST,
        MAX_SUBS,
        scopeToScopeName,
        TwitchProtocolChannelSchema,
    } from './TwitchConfigEditor';
    import TwitchAuthWizard from './TwitchAuthWizard.svelte';
    import IconButton from '$lib/components/IconButton.svelte';
    import TwitchChannelEditor from './TwitchChannelEditor.svelte';

    const props: Props = $props();
    const formState = new FormState(
        FormSchema,
        props.definition?.config.$type === 'Twitch'
            ? ($state.snapshot(props.definition) as ConnectionDefinition<TwitchProtocolConfiguration>)
            : undefined,
        async (data) => {
            await props.onsubmit?.($state.snapshot(data));
        },
    );

    let isAuthShown = $state(false);
    let editingChannel: TwitchProtocolChannel | null = $state(null);

    export const submit = () => formState.submit();
</script>

<TwitchAuthWizard
    show={isAuthShown}
    onsuccess={(auth: TwitchAuth) => {
        const oldChannel = formState.data.config.auth.me;
        formState.data.config.auth = auth;
        if (oldChannel !== auth.me) {
            formState.data.config.channels = [{ ...TwitchProtocolChannelSchema.getDefault(), name: auth.me }];
        }
        isAuthShown = false;
    }}
    onclose={() => {
        isAuthShown = false;
    }}
/>

<TwitchChannelEditor
    show={!!editingChannel}
    channel={editingChannel ?? undefined}
    is-mine={editingChannel?.name.toLowerCase() === formState.data.config.auth.me.toLowerCase()}
    onsuccess={(newChannel: TwitchProtocolChannel) => {
        const newChannels: (TwitchProtocolChannel | null)[] = [...formState.data.config.channels];
        let found = false;
        for (let i = 0; i < newChannels.length; i++) {
            if (newChannels[i]?.name === newChannel.name) {
                newChannels[i] = null;
            }

            if (newChannels[i]?.name === editingChannel?.name) {
                newChannels[i] = newChannel;
                found = true;
            }
        }
        if (!found) {
            newChannels.push(newChannel);
        }
        formState.data.config.channels = newChannels.filter((channel) => !!channel);
        editingChannel = null;
    }}
    onclose={() => {
        editingChannel = null;
    }}
/>

<Form
    novalidate
    onsubmit={async (e: SubmitEvent) => {
        e.preventDefault();
        e.stopPropagation();
        await formState.submit();
    }}
    class="d-flex flex-column w-100"
    style="gap: 1rem"
>
    <FormGroup>
        <Label>Name</Label>
        <Input
            name="name"
            bind:value={formState.data.name}
            invalid={!!formState.validationErrors.name}
            disabled={props.disabled}
            autocomplete="off"
        />
        <FormText>
            Name is an identifier for the connection. It can be anything as long as it is informative for you.
        </FormText>
        <FormFeedback valid={!formState.validationErrors.name}>
            {formState.validationErrors.name}
        </FormFeedback>
    </FormGroup>

    <div class="d-flex flex-column align-items-center" style:gap="1rem">
        <Button
            size="lg"
            onclick={(e: MouseEvent) => {
                e.preventDefault();
                isAuthShown = true;
            }}
            color="primary"
            style="width: calc(min(100%, 40rem))"
        >
            Connect Twitch account
        </Button>

        <Alert
            color={formState.data.config.auth.me !== '' ? 'success' : 'warning'}
            style="width: calc(min(100%, 40rem))"
        >
            <p class="fs-4 text-center my-0">
                {#if formState.data.config.auth.me === ''}
                    Not logged in
                {:else}
                    <span>Logged in as <strong>{formState.data.config.auth.me}</strong></span>
                {/if}
            </p>
        </Alert>
    </div>

    {#if formState.data.config.auth.me !== ''}
        <Card>
            <CardHeader>Granted API scopes</CardHeader>
            <CardBody>
                <span class="font-monospace"
                    >{formState.data.config.auth.scopes.map((scope) => scopeToScopeName.get(scope)).join(', ')}</span
                >
            </CardBody>
            <CardFooter
                ><a href="https://dev.twitch.tv/docs/authentication/scopes/" target="_blank" rel="noreferrer"
                    >Documentation</a
                ></CardFooter
            >
        </Card>
    {/if}

    <FormGroup>
        <Input
            type="switch"
            label="Receive updates"
            bind:checked={formState.data.config.receiveEvents}
            invalid={!!formState.validationErrors['config.receiveEvents']}
            disabled={props.disabled === true || formState.data.config.auth.me === ''}
        />
        <FormText>
            If this option is enabled, in addition to allowing the bot to access the Twitch Bot API, it will also keep
            an active connection and receive new events from Twitch (e.g., messages and commands).
        </FormText>
        <FormFeedback valid={!formState.validationErrors['config.receiveEvents']}>
            {formState.validationErrors['config.receiveEvents']}
        </FormFeedback>
    </FormGroup>

    {#if formState.data.config.auth.me !== ''}
        <FormGroup>
            <Label>Channels</Label>
            <div>
                {#each formState.data.config.channels as channel (channel.name)}
                    <InputGroup class="float-start me-2 mb-2" style="width: 15rem">
                        <Input value={channel.name} readonly />
                        <IconButton
                            icon="gear-fill"
                            tooltip="Edit properties"
                            style="width: 2.5em; height: 2.5em; padding: 0.5em"
                            variant="outline-success"
                            onclick={(e: MouseEvent) => {
                                e.preventDefault();
                                editingChannel = channel;
                            }}
                            disabled={props.disabled === true || formState.data.config.auth.me === ''}
                        />
                        <IconButton
                            icon="trash3-fill"
                            tooltip="Delete channel"
                            style="width: 2.5em; height: 2.5em; padding: 0.5em"
                            variant="outline-danger"
                            onclick={(e: MouseEvent) => {
                                e.preventDefault();
                                formState.data.config.channels.splice(
                                    formState.data.config.channels.indexOf(channel),
                                    1,
                                );
                            }}
                            disabled={props.disabled === true ||
                                formState.data.config.auth.me === '' ||
                                formState.data.config.auth.me.toLowerCase() === channel.name.toLowerCase()}
                        />
                    </InputGroup>
                {/each}

                <IconButton
                    icon="plus-lg"
                    tooltip="Add channel"
                    style="height: 2.5em"
                    variant="primary"
                    onclick={(e: MouseEvent) => {
                        e.preventDefault();
                        editingChannel = TwitchProtocolChannelSchema.getDefault();
                    }}
                    disabled={props.disabled === true ||
                        formState.data.config.auth.me === '' ||
                        formState.data.config.channels.length >= 100}
                ></IconButton>
            </div>
        </FormGroup>

        <Alert
            color={countSubs(formState.data.config.channels) <= MAX_SUBS &&
            countCost(formState.data.config.auth.me, formState.data.config.channels) <= MAX_COST
                ? 'success'
                : 'danger'}
        >
            <p class="fs-4 mb-2">Limits</p>
            Twitch has strict limits on the amount of events bots can subscribe to at once. The current known limits are:
            <br />
            <span>
                <strong>{countSubs(formState.data.config.channels)} / {MAX_SUBS}</strong> total subscriptions
            </span>
            <br />
            <span
                ><strong>{countCost(formState.data.config.auth.me, formState.data.config.channels)} / {MAX_COST}</strong
                > total cost</span
            >
            <p class="mt-2 mb-0">
                These limits are subject to change and are partially undocumented. Subscribing to a large number topics
                can also negatively affect startup times, so it is recommended to only subscribe to topics that are
                absolutely necessary.
            </p>
        </Alert>
    {/if}

    <FormGroup>
        <Label>Proxy</Label>
        <Input
            type="select"
            name="config.proxyId"
            bind:value={formState.data.config.proxyId}
            invalid={!!formState.validationErrors['config.proxyId']}
            disabled={props.disabled}
        >
            <option value="">Don&apos;t use a proxy</option>
            {#each Proxies.provider?.list as proxy (proxy.data.id)}
                <option value={proxy.data.id}>{proxy.data.name}</option>
            {/each}
        </Input>
        <FormText>Use a proxy server for outgoing connections.</FormText>
        <FormFeedback valid={!formState.validationErrors['config.proxyId']}>
            {formState.validationErrors['config.proxyId']}
        </FormFeedback>
    </FormGroup>
</Form>
