// Bottleneko.Client/src/lib/features/connections/protocols/TwitchAuthWizard.svelte
<script lang="ts">
    import { TwitchScopeValues, type TwitchScope } from '$lib/api/dtos.gen';
    import ModalDialog from '$lib/components/ModalDialog.svelte';
    import {
        Alert,
        Button,
        Card,
        CardBody,
        CardHeader,
        Form,
        FormFeedback,
        FormGroup,
        FormText,
        Input,
        Label,
    } from '@sveltestrap/sveltestrap';
    import {
        BOTTLENEKO_CLIENT_ID,
        schema,
        type Props,
        type TwitchAuthConfig,
        type TwitchAuthStage,
        type TwitchAuthSuccess,
        type TwitchVerification,
    } from './TwitchAuthWizard';
    import { FormState } from '$lib/FormState.svelte';
    import {
        chatScopes,
        createClipsScopes,
        editChannelInfoScopes,
        editUserInfoScopes,
        moderateScopes,
        scopeNameToScope,
        scopeToScopeName,
        viewChannelInfoScopes,
        viewUserInfoScopes,
        whispersScopes,
    } from './TwitchConfigEditor';
    import LoadingBanner from '$lib/components/LoadingBanner.svelte';
    import { onDestroy } from 'svelte';
    import { SvelteSet } from 'svelte/reactivity';

    class Authorizer {
        private inProgress = false;
        private destroyed = false;
        private abort = new AbortController();
        private config: TwitchAuthConfig;
        private verification: TwitchVerification;
        private timer: ReturnType<typeof setInterval>;

        constructor(config: TwitchAuthConfig, verification: TwitchVerification) {
            this.config = config;
            this.verification = verification;
            this.timer = setInterval(() => {
                void this.onTimer();
            }, 3000);
        }

        async onTimer() {
            if (this.inProgress) {
                return;
            }

            this.inProgress = true;
            try {
                const formData = new FormData();
                formData.append(
                    'client_id',
                    this.config.clientId.trim() === '' ? BOTTLENEKO_CLIENT_ID : this.config.clientId.trim(),
                );
                formData.append('scopes', this.config.scopes.map((scope) => scopeToScopeName.get(scope)).join(' '));
                formData.append('device_code', this.verification.device_code);
                formData.append('grant_type', 'urn:ietf:params:oauth:grant-type:device_code');

                const response = await fetch('https://id.twitch.tv/oauth2/token', {
                    method: 'POST',
                    body: formData,
                    signal: this.abort.signal,
                });
                const json = (await response.json()) as never;

                if (this.destroyed) {
                    return;
                }

                if (response.status === 400) {
                    const result = json as { status: number; message: string };
                    switch (result.message) {
                        case 'authorization_pending':
                            // everything is okay, keep waiting
                            break;

                        case 'invalid device code':
                        default:
                            console.error('Twitch auth failed:', result.message);
                            stage = { id: 'authorization-failed', config: this.config };
                            break;
                    }
                } else if (response.status === 200) {
                    const result = json as TwitchAuthSuccess;

                    stage = { id: 'loading-user-data', config: this.config };

                    const me = (await (
                        await fetch('https://api.twitch.tv/helix/users', {
                            method: 'GET',
                            headers: {
                                Authorization: `Bearer ${result.access_token}`,
                                'Client-Id':
                                    this.config.clientId.trim() === ''
                                        ? BOTTLENEKO_CLIENT_ID
                                        : this.config.clientId.trim(),
                            },
                            signal: this.abort.signal,
                        })
                    ).json()) as { data: { id: string; login: string; display_name: string }[] };

                    // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
                    if (this.destroyed) {
                        return;
                    }

                    props.onsuccess({
                        clientId:
                            this.config.clientId.trim() === '' ? BOTTLENEKO_CLIENT_ID : this.config.clientId.trim(),
                        me: me.data[0].display_name,
                        accessToken: result.access_token,
                        refreshToken: result.refresh_token,
                        scopes: result.scope.map((scope) => scopeNameToScope[scope]),
                    });
                }
            } catch (err: unknown) {
                console.error('Twitch API request failed:', err);
                stage = { id: 'authorization-failed', config: this.config };
            } finally {
                this.inProgress = false;
            }
        }

        destroy() {
            if (this.destroyed) {
                return;
            }

            this.destroyed = true;
            clearInterval(this.timer);
            this.abort.abort();
        }
    }

    let authorizer: Authorizer | null = null;

    const { show = false, ...props }: Props = $props();
    let stage: TwitchAuthStage = $state.raw({ id: 'start' });
    const formState = $derived(
        new FormState(schema, undefined, async (data) => {
            await requestVerification(data);
        }),
    );
    let showAdvancedOptions = $state(false);

    const areScopesEnabled = (required: TwitchScope[]) => {
        return required.map((scope) => formState.data.scopes.includes(scope)).reduce((a, b) => a && b);
    };

    const enableScopes = (enable: TwitchScope[]) => {
        formState.data.scopes = [...new SvelteSet([...formState.data.scopes, ...enable])];
    };
    const disableScopes = (disable: TwitchScope[]) => {
        const set = new SvelteSet(formState.data.scopes);
        disable.forEach((scope) => set.delete(scope));
        formState.data.scopes = [...set];
    };
    const toggleScopes = (toggle: TwitchScope[]) => {
        if (areScopesEnabled(toggle)) {
            disableScopes(toggle);
        } else {
            enableScopes(toggle);
        }
    };

    const requestVerification = async (config: TwitchAuthConfig) => {
        stage = { id: 'requesting-verification', config };
        try {
            const formData = new FormData();
            formData.append('client_id', config.clientId.trim() === '' ? BOTTLENEKO_CLIENT_ID : config.clientId.trim());
            formData.append('scopes', config.scopes.map((scope) => scopeToScopeName.get(scope)).join(' '));

            const result = await fetch('https://id.twitch.tv/oauth2/device', {
                method: 'POST',
                body: formData,
            });

            const verification = (await result.json()) as TwitchVerification;
            stage = { id: 'ready-for-authorization', config, verification };
        } catch (err: unknown) {
            console.error('Twitch API request failed:', err);
            stage = { id: 'authorization-failed', config };
        }
    };

    $effect(() => {
        if (stage.id === 'ready-for-authorization') {
            authorizer?.destroy();
            authorizer = null;
            authorizer = new Authorizer(stage.config, stage.verification);
        } else if (stage.id !== 'loading-user-data') {
            authorizer?.destroy();
            authorizer = null;
        }
    });

    onDestroy(() => {
        authorizer?.destroy();
        authorizer = null;
    });

    $effect(() => {
        if (show) {
            stage = { id: 'start' };
            formState.data = formState.getDefault();
        } else {
            authorizer?.destroy();
            authorizer = null;
        }
    });
</script>

<ModalDialog title="Connect Twitch account" {show} onclose={props.onclose} size="lg">
    {#if stage.id === 'start'}
        <Form
            novalidate
            onsubmit={async (e: SubmitEvent) => {
                await formState.submit(e);
            }}
            class="d-flex flex-column p-2"
            style="gap: 1rem"
        >
            <Card>
                <CardHeader class="fw-bold">Permissions</CardHeader>
                <CardBody class="d-flex flex-column p-3" style="gap: 1rem">
                    <Input
                        type="switch"
                        label="Access to chat"
                        bind:checked={
                            () => {
                                return areScopesEnabled(chatScopes);
                            },
                            () => {
                                toggleScopes(chatScopes);
                            }
                        }
                    />

                    <Input
                        type="switch"
                        label="Access to whispers (direct messages)"
                        bind:checked={
                            () => {
                                return areScopesEnabled(whispersScopes);
                            },
                            () => {
                                toggleScopes(whispersScopes);
                            }
                        }
                    />

                    <Input
                        type="switch"
                        label="View user information"
                        bind:checked={
                            () => {
                                return areScopesEnabled(viewUserInfoScopes);
                            },
                            () => {
                                toggleScopes(viewUserInfoScopes);
                            }
                        }
                    />

                    <Input
                        type="switch"
                        label="Edit user information"
                        bind:checked={
                            () => {
                                return areScopesEnabled(editUserInfoScopes);
                            },
                            () => {
                                toggleScopes(editUserInfoScopes);
                            }
                        }
                    />

                    <Input
                        type="switch"
                        label="View channel information"
                        bind:checked={
                            () => {
                                return areScopesEnabled(viewChannelInfoScopes);
                            },
                            () => {
                                toggleScopes(viewChannelInfoScopes);
                            }
                        }
                    />

                    <Input
                        type="switch"
                        label="Edit channel information"
                        bind:checked={
                            () => {
                                return areScopesEnabled(editChannelInfoScopes);
                            },
                            () => {
                                toggleScopes(editChannelInfoScopes);
                            }
                        }
                    />

                    <Input
                        type="switch"
                        label="Moderate chat"
                        bind:checked={
                            () => {
                                return areScopesEnabled(moderateScopes);
                            },
                            () => {
                                toggleScopes(moderateScopes);
                            }
                        }
                    />

                    <Input
                        type="switch"
                        label="Create clips"
                        bind:checked={
                            () => {
                                return areScopesEnabled(createClipsScopes);
                            },
                            () => {
                                toggleScopes(createClipsScopes);
                            }
                        }
                    />
                </CardBody>
            </Card>

            <Input type="switch" label="Show advanced options" bind:checked={showAdvancedOptions} />

            {#if showAdvancedOptions}
                <FormGroup>
                    <Label>Client ID</Label>
                    <Input
                        bind:value={formState.data.clientId}
                        invalid={!!formState.validationErrors.clientId}
                        autocomplete="off"
                    />
                    <FormText>
                        Client ID is a unique application identifier provided by Twitch. You can request your own Client
                        ID by registering your bot in the <a
                            href="https://dev.twitch.tv/console/apps/create"
                            target="_blank"
                            rel="noreferrer">Twitch Developer Portal</a
                        > or leave empty to use the one provided by Bottleneko. If you are using your own Client ID, please
                        make sure that the Client Type option is set to Public in the Developer Portal.
                    </FormText>
                    <FormFeedback valid={!formState.validationErrors.clientId}>
                        {formState.validationErrors.clientId}
                    </FormFeedback>
                </FormGroup>

                <Card>
                    <CardHeader class="fw-bold">Customize API scopes</CardHeader>
                    <CardBody class="d-flex flex-column p-3" style="gap: 1rem">
                        {#each TwitchScopeValues as scope (scope)}
                            <Input
                                type="switch"
                                label={scopeToScopeName.get(scope)}
                                bind:checked={
                                    () => {
                                        return areScopesEnabled([scope]);
                                    },
                                    () => {
                                        toggleScopes([scope]);
                                    }
                                }
                            />
                            <a href="https://dev.twitch.tv/docs/authentication/scopes/" target="_blank" rel="noreferrer"
                                >Documentation</a
                            >
                        {/each}
                    </CardBody>
                </Card>
            {/if}
        </Form>
    {:else if stage.id === 'requesting-verification'}
        <LoadingBanner />
    {:else if stage.id === 'ready-for-authorization'}
        <div class="d-flex justify-content-center pb-3">
            <Button
                size="lg"
                color="primary"
                href={stage.verification.verification_uri}
                target="_blank"
                rel="noreferrer">Authorize Bottleneko</Button
            >
        </div>

        <Card>
            <CardHeader>Activation Code</CardHeader>
            <CardBody>
                <Form>
                    <div class="d-flex justify-content-center">
                        <Input
                            style="max-width: 15rem; font-size: 2rem; font-weight: bold; text-align: center"
                            type="text"
                            readonly
                            defaultValue={stage.verification.user_code}
                        />
                    </div>

                    <FormText>
                        The &apos;Authorize Bottleneko&apos; button will open the Twitch device activation page in a new
                        tab. Please make sure that the activation code matches the one shown above. Once you have
                        successfully authorized Bottleneko, this form will close automatically.
                    </FormText>
                </Form>
            </CardBody>
        </Card>
    {:else if stage.id === 'loading-user-data'}
        <LoadingBanner />
    {:else if stage.id === 'authorization-failed'}
        <Alert color="danger">
            <p class="fs-4">Authorization failed</p>

            Twitch returned an error. Please try again later.
        </Alert>
    {/if}

    {#snippet footer()}
        {#if stage.id === 'start'}
            <Button onclick={props.onclose} color="secondary">Back</Button>
            <Button
                onclick={() => {
                    void formState.submit();
                }}
                color="primary">Next</Button
            >
        {:else if stage.id === 'requesting-verification'}
            <Button disabled color="secondary">Back</Button>
            <Button disabled color="primary">Next</Button>
        {:else if stage.id === 'ready-for-authorization'}
            <Button
                onclick={() => {
                    stage = { id: 'start', config: stage.config };
                }}
                color="secondary">Back</Button
            >
            <Button disabled color="primary">Next</Button>
        {:else if stage.id === 'loading-user-data'}
            <Button disabled color="secondary">Back</Button>
            <Button disabled color="primary">Next</Button>
        {:else if stage.id === 'authorization-failed'}
            <Button
                onclick={() => {
                    stage = { id: 'start', config: stage.config };
                }}
                color="secondary">Back</Button
            >
            <Button disabled color="primary">Next</Button>
        {/if}
    {/snippet}
</ModalDialog>

// Bottleneko.Client/src/features/connections/twitch/TwitchAuthWizard.tsx
import { useCallback, useEffect, useRef, useState } from 'react';
import * as yup from 'yup';
import { Formik } from 'formik';
import { Alert, Button, Card, Form } from 'react-bootstrap';
import ModalDialog from '../../../components/modal-dialog/ModalDialog';
import { useAsync, useInterval } from '../../../app/hooks';
import LoadingBanner from '../../../components/LoadingBanner';
import { TwitchScope } from '../../api/dtos.gen';
import * as scopes from './scopes';
import { TwitchAuth } from '.';

const BOTTLENEKO_CLIENT_ID = 'd7nyymm5khoc85v7urm5unjikw9gy2';

const schema = yup.object().shape({
    clientId: yup.string().default(''),
    scopes: yup.array().of(yup.mixed<TwitchScope>().oneOf(Object.values(TwitchScope)).required()).default([...scopes.chatScopes, ...scopes.viewUserInfoScopes, ...scopes.viewChannelInfoScopes]),
});

type TwitchAuthConfig = yup.InferType<typeof schema>;
const defaultConfig = schema.getDefault();

interface TwitchVerification {
    device_code: string;
    expires_in: number;
    interval: number;
    user_code: string;
    verification_uri: string;
}

interface TwitchAuthSuccess {
    access_token: string;
    expires_in: number;
    refresh_token: string;
    scope: string[];
    token_type: string;
}

type TwitchAuthStage =
    { id: 'start'; config?: TwitchAuthConfig } |
    { id: 'requesting-verification'; config: TwitchAuthConfig } |
    { id: 'ready-for-authorization'; config: TwitchAuthConfig; verification: TwitchVerification } |
    { id: 'loading-user-data'; config: TwitchAuthConfig } |
    { id: 'authorization-failed'; config: TwitchAuthConfig };

export default function TwitchAuthWizard({ show, onSuccess, onCancel }: { show: boolean; onSuccess: (auth: TwitchAuth) => void; onCancel: () => void }) {
    const [stage, setStage] = useState<TwitchAuthStage>({ id: 'start' });
    const [showAdvancedOptions, setShowAdvancedOptions] = useState(false);
    const formRef = useRef<HTMLFormElement>(null);

    const areScopesEnabled = (scopes: TwitchScope[], required: TwitchScope[]) => {
        return required.map(scope => scopes.includes(scope)).reduce((a, b) => a && b);
    };

    const enableScopes = (scopes: TwitchScope[], enable: TwitchScope[]) => [...new Set([...scopes, ...enable])];
    const disableScopes = (scopes: TwitchScope[], disable: TwitchScope[]) => {
        const set = new Set(scopes);
        disable.forEach(scope => set.delete(scope));
        return [...set];
    };
    const toggleScopes = (scopes: TwitchScope[], toggle: TwitchScope[]) => {
        if (areScopesEnabled(scopes, toggle)) {
            return disableScopes(scopes, toggle);
        }
        else {
            return enableScopes(scopes, toggle);
        }
    };

    const prevShown = useRef(show);
    useEffect(() => {
        if (!prevShown.current && show) {
            setStage({ id: 'start' });
        }
        prevShown.current = show;
    }, [show]);

    const currentUpdateRef = useRef<object | null>(null);
    const whichUpdateRef = useRef({});
    useInterval(useCallback(() => {
        if (currentUpdateRef.current !== null || stage.id !== 'ready-for-authorization') {
            return;
        }
        currentUpdateRef.current = whichUpdateRef.current;

        void (async () => {
            try {
                if (currentUpdateRef.current !== whichUpdateRef.current) {
                    return;
                }

                const formData = new FormData();
                formData.append('client_id', stage.config.clientId.trim() === '' ? BOTTLENEKO_CLIENT_ID : stage.config.clientId.trim());
                formData.append('scopes', stage.config.scopes.map(scope => scopes.scopeToScopeName.get(scope)).join(' '));
                formData.append('device_code', stage.verification.device_code);
                formData.append('grant_type', 'urn:ietf:params:oauth:grant-type:device_code');

                const response = await fetch('https://id.twitch.tv/oauth2/token', {
                    method: 'POST',
                    body: formData,
                });
                const json = await response.json() as never;

                if (currentUpdateRef.current !== whichUpdateRef.current) {
                    return;
                }

                if (response.status === 400) {
                    const result = json as { status: number; message: string };
                    switch (result.message) {
                        case 'authorization_pending':
                            // everything is okay, keep waiting
                            break;

                        case 'invalid device code':
                        default:
                            console.error('twitch auth failed', result.message);
                            setStage({ id: 'authorization-failed', config: stage.config });
                            break;
                    }
                }
                else if (response.status === 200) {
                    const result = json as TwitchAuthSuccess;

                    setStage({ id: 'loading-user-data', config: stage.config });

                    const me = await (await fetch('https://api.twitch.tv/helix/users', {
                        method: 'GET',
                        headers: {
                            'Authorization': `Bearer ${result.access_token}`,
                            'Client-Id': stage.config.clientId.trim() === '' ? BOTTLENEKO_CLIENT_ID : stage.config.clientId.trim(),
                        },
                    })).json() as { data: { id: string; login: string; display_name: string }[] };
                    onSuccess({
                        clientId: stage.config.clientId.trim() === '' ? BOTTLENEKO_CLIENT_ID : stage.config.clientId.trim(),
                        me: me.data[0].display_name,
                        accessToken: result.access_token,
                        refreshToken: result.refresh_token,
                        scopes: result.scope.map(scope => scopes.scopeNameToScope[scope]),
                    });
                }
            }
            catch {
                setStage({ id: 'authorization-failed', config: stage.config });
            }
            finally {
                currentUpdateRef.current = null;
            }
        })();
    }, [stage, onSuccess]), 3000);

    useEffect(() => {
        return () => {
            whichUpdateRef.current = {};
        };
    }, [stage]);

    const [requestVerification] = useAsync(useCallback(async (config: TwitchAuthConfig) => {
        setStage({ id: 'requesting-verification', config });
        try {
            const formData = new FormData();
            formData.append('client_id', config.clientId.trim() === '' ? BOTTLENEKO_CLIENT_ID : config.clientId.trim());
            formData.append('scopes', config.scopes.map(scope => scopes.scopeToScopeName.get(scope)).join(' '));

            const result = await fetch('https://id.twitch.tv/oauth2/device', {
                method: 'POST',
                body: formData,
            });

            const verification = await result.json() as TwitchVerification;
            setStage({ id: 'ready-for-authorization', config, verification });
        }
        catch (err) {
            console.error('Twitch API request failed:', err);
            setStage({ id: 'authorization-failed', config });
        }
    }, []));

    switch (stage.id) {
        case 'start':
            return (
                <ModalDialog
                    title="Connect Twitch account"
                    show={show}
                    onCancel={onCancel}
                >
                    <Formik validationSchema={schema} onSubmit={requestVerification} initialValues={stage.config ?? defaultConfig} validateOnChange={false}>
                        {({ handleSubmit, handleChange, setFieldValue, values, errors }) => (
                            <Form
                                noValidate
                                onSubmit={(e) => {
                                    e.preventDefault();
                                    e.stopPropagation();
                                    handleSubmit();
                                }}
                                className="d-flex flex-column p-2"
                                style={{ gap: '1rem' }}
                                ref={formRef}
                            >
                                <Card>
                                    <Card.Header className="fw-bold">Permissions</Card.Header>
                                    <Card.Body className="d-flex flex-column p-3" style={{ gap: '1rem' }}>
                                        <Form.Switch
                                            label="Access to chat"
                                            checked={areScopesEnabled(values.scopes, scopes.chatScopes)}
                                            onChange={() => void setFieldValue('scopes', toggleScopes(values.scopes, scopes.chatScopes))}
                                        />

                                        <Form.Switch
                                            label="Access to whispers (direct messages)"
                                            checked={areScopesEnabled(values.scopes, scopes.whispersScopes)}
                                            onChange={() => void setFieldValue('scopes', toggleScopes(values.scopes, scopes.whispersScopes))}
                                        />

                                        <Form.Switch
                                            label="View user information"
                                            checked={areScopesEnabled(values.scopes, scopes.viewUserInfoScopes)}
                                            onChange={() => void setFieldValue('scopes', toggleScopes(values.scopes, scopes.viewUserInfoScopes))}
                                        />

                                        <Form.Switch
                                            label="Edit user information"
                                            checked={areScopesEnabled(values.scopes, scopes.editUserInfoScopes)}
                                            onChange={() => void setFieldValue('scopes', toggleScopes(values.scopes, scopes.editUserInfoScopes))}
                                        />

                                        <Form.Switch
                                            label="View channel information"
                                            checked={areScopesEnabled(values.scopes, scopes.viewChannelInfoScopes)}
                                            onChange={() => void setFieldValue('scopes', toggleScopes(values.scopes, scopes.viewChannelInfoScopes))}
                                        />

                                        <Form.Switch
                                            label="Edit channel information"
                                            checked={areScopesEnabled(values.scopes, scopes.editChannelInfoScopes)}
                                            onChange={() => void setFieldValue('scopes', toggleScopes(values.scopes, scopes.editChannelInfoScopes))}
                                        />

                                        <Form.Switch
                                            label="Moderate chat"
                                            checked={areScopesEnabled(values.scopes, scopes.moderateScopes)}
                                            onChange={() => void setFieldValue('scopes', toggleScopes(values.scopes, scopes.moderateScopes))}
                                        />

                                        <Form.Switch
                                            label="Create clips"
                                            checked={areScopesEnabled(values.scopes, scopes.createClipsScopes)}
                                            onChange={() => void setFieldValue('scopes', toggleScopes(values.scopes, scopes.createClipsScopes))}
                                        />
                                    </Card.Body>
                                </Card>

                                <Form.Switch
                                    label="Show advanced options"
                                    checked={showAdvancedOptions}
                                    onChange={() => { setShowAdvancedOptions(!showAdvancedOptions); }}
                                />

                                {
                                    showAdvancedOptions
                                        ? (
                                                <>
                                                    <Form.Group>
                                                        <Form.Label>Client ID</Form.Label>
                                                        <Form.Control name="clientId" value={values.clientId} onChange={handleChange} isInvalid={!!errors.clientId} autoComplete="off" />
                                                        <Form.Text muted>
                                                            Client ID is a unique application identifier provided by Twitch. You can request your own Client ID by registering your bot in the
                                                            {' '}
                                                            <a href="https://dev.twitch.tv/console/apps/create" target="_blank" rel="noreferrer">Twitch Developer Portal</a>
                                                            {' '}
                                                            or leave empty to use the one provided by Bottleneko. If you are using your own Client ID, please make sure that the Client Type option is set to Public in the Developer Portal.
                                                        </Form.Text>
                                                        <Form.Control.Feedback type="invalid">
                                                            {errors.clientId}
                                                        </Form.Control.Feedback>
                                                    </Form.Group>

                                                    <Card>
                                                        <Card.Header className="fw-bold">Customize API scopes</Card.Header>
                                                        <Card.Body className="d-flex flex-column p-3" style={{ gap: '1rem' }}>
                                                            {
                                                                Object.values(TwitchScope).map(scope => (
                                                                    <Form.Switch
                                                                        key={scope}
                                                                        label={scopes.scopeToScopeName.get(scope)}
                                                                        checked={areScopesEnabled(values.scopes, [scope])}
                                                                        onChange={() => void setFieldValue('scopes', toggleScopes(values.scopes, [scope]))}
                                                                    />
                                                                ))
                                                            }
                                                            <a href="https://dev.twitch.tv/docs/authentication/scopes/" target="_blank" rel="noreferrer">Documentation</a>
                                                        </Card.Body>
                                                    </Card>
                                                </>
                                            )
                                        : <></>
                                }
                            </Form>
                        )}
                    </Formik>

                    <ModalDialog.Button onClick={onCancel} variant="secondary">Back</ModalDialog.Button>
                    <ModalDialog.Button onClick={() => { formRef.current?.requestSubmit(); }}>Next</ModalDialog.Button>
                </ModalDialog>
            );

        case 'requesting-verification':
            return (
                <ModalDialog
                    title="Connect Twitch account"
                    show={show}
                    onCancel={onCancel}
                >
                    <LoadingBanner />

                    <ModalDialog.Button variant="secondary" disabled>Back</ModalDialog.Button>
                    <ModalDialog.Button disabled>Next</ModalDialog.Button>
                </ModalDialog>
            );

        case 'ready-for-authorization':
            return (
                <ModalDialog
                    title="Connect Twitch account"
                    show={show}
                    onCancel={onCancel}
                >
                    <div className="d-flex justify-content-center pb-3">
                        <Button size="lg" as="a" href={stage.verification.verification_uri} target="_blank" rel="noreferrer">Authorize Bottleneko</Button>
                    </div>

                    <Card>
                        <Card.Header>Activation Code</Card.Header>
                        <Card.Body>
                            <Form>
                                <div className="d-flex justify-content-center">
                                    <Form.Control style={{ maxWidth: '15rem', fontSize: '2rem', fontWeight: 'bold', textAlign: 'center' }} type="text" readOnly={true} defaultValue={stage.verification.user_code} />
                                </div>

                                <Form.Text muted>
                                    The &apos;Authorize Bottleneko&apos; button will open the Twitch device activation page in a new tab. Please make sure that the activation code matches the one shown above. Once you have successfully authorized Bottleneko, this form will close automatically.
                                </Form.Text>
                            </Form>
                        </Card.Body>
                    </Card>

                    <ModalDialog.Button onClick={() => { setStage({ id: 'start', config: stage.config }); }} variant="secondary">Back</ModalDialog.Button>
                    <ModalDialog.Button disabled>Next</ModalDialog.Button>
                </ModalDialog>
            );

        case 'loading-user-data':
            return (
                <ModalDialog
                    title="Connect Twitch account"
                    show={show}
                    onCancel={onCancel}
                >
                    <LoadingBanner />

                    <ModalDialog.Button variant="secondary" disabled>Back</ModalDialog.Button>
                    <ModalDialog.Button disabled>Next</ModalDialog.Button>
                </ModalDialog>
            );

        case 'authorization-failed':
            return (
                <ModalDialog
                    title="Connect Twitch account"
                    show={show}
                    onCancel={onCancel}
                >
                    <Alert variant="danger">
                        <p className="fs-4">Authorization failed</p>

                        Twitch returned an error. Please try again later.
                    </Alert>

                    <ModalDialog.Button onClick={() => { setStage({ id: 'start', config: stage.config }); }} variant="secondary">Back</ModalDialog.Button>
                    <ModalDialog.Button disabled>Next</ModalDialog.Button>
                </ModalDialog>
            );

        default:
            return <></>;
    }
}
