// Bottleneko.Client/src/features/log/LogSourceDisplay.tsx
﻿import { Link } from 'react-router-dom';
import { Button } from 'react-bootstrap';
import { LogSourceType } from '../api/dtos.gen';
import { useConnections } from '../connections/context';
import { useScripts } from '../scripts/context';
import ProtocolIcon from '../connections/ProtocolIcon';

export default function LogSourceDisplay({ sourceType, sourceId }: { sourceType: LogSourceType; sourceId: string }) {
    const connections = useConnections();
    const scripts = useScripts();

    switch (sourceType) {
        case LogSourceType.System:
            return (
                <Button className="px-1 py-0" size="sm">
                    System
                </Button>
            );

        case LogSourceType.Connection:
            return (
                <Link to={`/connections/${sourceId}`} className="btn btn-success btn-sm px-1 py-0">
                    <ProtocolIcon protocol={connections?.state.list?.find(connection => connection.data.id === sourceId)?.data.protocol} />
                    {' '}
                    {connections?.state.list?.find(connection => connection.data.id === sourceId)?.data.name ?? `Connection #${sourceId}`}
                </Link>
            );

        case LogSourceType.Script:
            return (
                <Link to={`/scripts/${sourceId}`} className="btn btn-warning btn-sm px-1 py-0">
                    {scripts?.state.list?.find(script => script.data.id === sourceId)?.data.name ?? `Script #${sourceId}`}
                </Link>
            );

        default:
            return <></>;
    }
}

// src/Bottleneko.Client/src/lib/features/log/LogSourceDisplay.svelte
<script lang="ts">
    import { Button, Tooltip } from '@sveltestrap/sveltestrap';
    import ProtocolIcon from '../connections/ProtocolIcon.svelte';
    import { Connections } from '../connections';
    import { Scripts } from '../scripts';
    import type { Props } from './LogSourceDisplay';

    const props: Props = $props();

    let button: HTMLElement | undefined = $state();
</script>

{#if props.sourceType === 'System'}
    <Button class="text-collapse w-100 px-1 py-0" color="primary" size="sm">System</Button>
{:else if props.sourceType === 'Connection'}
    {@const connection = Connections.provider?.list?.find((connection) => connection.data.id === props.sourceId)}
    {#if connection}
        <Button href={`/connections/${props.sourceId}`} color="success" size="sm" class="text-collapse w-100 px-1 py-0">
            <ProtocolIcon protocol={connection.data.protocol} />
            {connection.data.name}
        </Button>
    {:else}
        <div class="w-100" bind:this={button}>
            <Button color="success" size="sm" class="text-collapse w-100 px-1 py-0" disabled>
                Connection #{props.sourceId}
            </Button>
        </div>

        <Tooltip target={button} theme="light" placement="bottom">
            The connection does not exist or has been deleted.
        </Tooltip>
    {/if}
{:else if props.sourceType === 'Script'}
    {@const script = Scripts.provider?.list?.find((script) => script.data.id === props.sourceId)}
    {#if script}
        <Button href={`/scripts/${props.sourceId}`} color="warning" size="sm" class="text-collapse w-100 px-1 py-0">
            {script.data.name}
        </Button>
    {:else}
        <div class="w-100" bind:this={button}>
            <Button color="warning" size="sm" class="text-collapse w-100 px-1 py-0" disabled>
                Script #{props.sourceId}
            </Button>
        </div>

        <Tooltip target={button} theme="light" placement="bottom">
            The script does not exist or has been deleted.
        </Tooltip>
    {/if}
{/if}
