// Bottleneko.Client/src/features/log/LogViewer.tsx
﻿import './LogViewer.css';
import { ToggleButton, ButtonGroup, Card, Table } from 'react-bootstrap';
import { useCallback, useState } from 'react';
import dateFormat from 'dateformat';
import { useSubscription } from '../websockets/hooks';
import { LogLetter, LogSeverity, LogSourceType } from '../api/dtos.gen';
import LoadingBanner from '../../components/LoadingBanner';
import LogSourceDisplay from './LogSourceDisplay';

type LogSeverityFilter = Record<LogSeverity, boolean>;

export default function LogViewer({ sourceType, sourceId }: { sourceType?: LogSourceType; sourceId?: string }) {
    const [severityFilter, setSeverityFilter] = useState<LogSeverityFilter>({
        [LogSeverity.Critical]: true,
        [LogSeverity.Error]: true,
        [LogSeverity.Warning]: true,
        [LogSeverity.Info]: true,
        [LogSeverity.Verbose]: false,
        [LogSeverity.Debug]: false,
    });

    const { events } = useSubscription<LogLetter>({
        subscription: {
            type: 'Logs',
            filter: {
                severities: Object.keys(severityFilter).filter(severity => severityFilter[severity as LogSeverity]) as LogSeverity[],
                sourceType: sourceType ?? null,
                sourceId: sourceId ?? null,
                category: null,
            },
        },
        maxEvents: 500,
    });

    const toggleSeverityFilter = useCallback((severity: LogSeverity) => {
        const newSeverityFilter = { ...severityFilter, [severity]: !severityFilter[severity] };
        setSeverityFilter(newSeverityFilter);
    }, [severityFilter]);

    const showSource = sourceType !== LogSourceType.Connection && sourceType !== LogSourceType.Script;

    const getSeverityButtonVariant = (severity: LogSeverity) => {
        switch (severity) {
            case LogSeverity.Critical:
            case LogSeverity.Error:
                return 'danger';

            case LogSeverity.Warning:
                return 'warning';

            case LogSeverity.Info:
                return 'primary';

            default:
                return 'secondary';
        }
    };

    return (
        <>
            <Card className="h-100" style={{ margin: '0.5em' }}>
                <Card.Body className="d-flex flex-column h-100" style={{ gap: '1em' }}>
                    <ButtonGroup style={{ maxWidth: '1000px' }}>
                        {
                            Object.keys(severityFilter).map(severity => (
                                <ToggleButton
                                    key={severity}
                                    variant={`outline-${getSeverityButtonVariant(severity as LogSeverity)}`}
                                    type="checkbox"
                                    id={`log-severity-${severity}`}
                                    className={severityFilter[severity as LogSeverity] ? '' : 'text-white'}
                                    value={severity}
                                    checked={severityFilter[severity as LogSeverity]}
                                    onChange={(e) => { toggleSeverityFilter(e.currentTarget.value as LogSeverity); }}
                                    style={{ }}
                                >
                                    {severity}
                                </ToggleButton>
                            ))
                        }
                    </ButtonGroup>

                    <div className="flex-grow-1" style={{ overflowY: 'scroll' }}>
                        <Table style={{ minWidth: '50em' }} size="sm" className="log-viewer">
                            <thead>
                                <tr>
                                    <th>Timestamp</th>
                                    {
                                        showSource
                                            ? <th>Source</th>
                                            : <></>
                                    }
                                    <th>Category</th>
                                    <th>Message</th>
                                </tr>
                            </thead>
                            <tbody>
                                {events && events.length > 0
                                    ? events.map(message => (
                                            <tr key={message.id} className={`log-message log-message-${message.severity.toLowerCase()} font-monospace`}>
                                                <td className="log-message-timestamp">{dateFormat(new Date(message.timestamp), 'yyyy-mm-dd HH:MM:ss.l')}</td>
                                                {
                                                    showSource
                                                        ? (
                                                                <td className="log-message-source">
                                                                    <LogSourceDisplay sourceType={message.sourceType} sourceId={message.sourceId} />
                                                                </td>
                                                            )
                                                        : <></>
                                                }

                                                <td className="log-message-category">{message.category}</td>
                                                <td className="log-message-text">{message.text}</td>
                                            </tr>
                                        ))
                                    : (
                                            <tr>
                                                <td colSpan={showSource ? 4 : 3} className="text-center">
                                                    {
                                                        events
                                                            ? <em className="text-secondary fst-italic">(no messages)</em>
                                                            : <LoadingBanner />
                                                    }
                                                </td>
                                            </tr>
                                        )}
                            </tbody>
                        </Table>
                    </div>
                </Card.Body>
            </Card>
        </>
    );
}

// src/Bottleneko.Client/src/lib/features/log/LogViewer.svelte
<script lang="ts">
    import './styles.scss';
    import { type LogSeverity } from '$lib/api/bottleneko.gen';
    import { LogSubscriber } from '../ws/WebSocketConnection.svelte';
    import { Button, ButtonGroup, Card, CardBody, CardHeader } from '@sveltestrap/sveltestrap';
    import { getSeverityButtonVariant, messageStyle, severityStyle, type Props } from './LogViewer';
    import dateFormat from 'dateformat';
    import LogSourceDisplay from './LogSourceDisplay.svelte';
    import { blur } from 'svelte/transition';
    import { flip } from 'svelte/animate';
    import LoadingBanner from '$lib/components/LoadingBanner.svelte';

    const props: Props = $props();

    let severityFilter: Record<LogSeverity, boolean> = $state({
        Critical: true,
        Error: true,
        Warning: true,
        Info: true,
        Verbose: false,
        Debug: false,
    });

    const toggleSeverityFilter = (severity: LogSeverity) => {
        severityFilter = { ...severityFilter, [severity]: !severityFilter[severity] };
    };

    const subscriber = new LogSubscriber();
    $effect(() => {
        subscriber.subscribe({
            severities: (Object.keys(severityFilter) as LogSeverity[]).filter((severity) => severityFilter[severity]),
            sourceType: props.sourceType ?? null,
            sourceId: props.sourceId ?? null,
            category: null,
        });
    });
</script>

<div class="h-100">
    <Card class="h-100" style="background-color: #141417">
        <CardHeader class="highlight d-flex flex-row align-items-center">
            <div style="flex-grow: 1">Log messages</div>
            <ButtonGroup style="max-width: 1000px">
                {#each Object.keys(severityFilter) as LogSeverity[] as severity (severity)}
                    <Button
                        color={getSeverityButtonVariant(severity, severityFilter[severity])}
                        class={severityFilter[severity] ? '' : 'text-white'}
                        onclick={() => {
                            toggleSeverityFilter(severity);
                        }}
                        size="sm"
                    >
                        {severity}
                    </Button>
                {/each}
            </ButtonGroup>
        </CardHeader>
        <CardBody style="overflow: hidden scroll">
            <div class="d-flex flex-column w-100 h-100">
                {#if subscriber.isLoading}
                    <LoadingBanner size="xl" />
                {:else if subscriber.mail.length === 0}
                    <div class="w-100 h-100 d-flex justify-content-center align-items-center">
                        <p class="text-secondary fst-italic" style="text-align: center">(no messages)</p>
                    </div>
                {:else}
                    {#each subscriber.mail as message (message.id)}
                        <div
                            class="font-monospace w-100 log-message"
                            style="line-height: 1.2em; padding: 0.2em"
                            in:blur|global={{ duration: 300 }}
                            animate:flip={{ duration: 300 }}
                        >
                            <span style="color: #707070"
                                >{dateFormat(new Date(message.timestamp), 'yyyy-mm-dd HH:MM:ss.l')}</span
                            >
                            {#if props.sourceType !== 'Connection' && props.sourceType !== 'Script'}
                                <div style="display: inline-block; width: 150px">
                                    <LogSourceDisplay sourceType={message.sourceType} sourceId={message.sourceId} />
                                </div>
                            {/if}
                            <span style="color: #707070">{message.category}</span>
                            <span style={severityStyle[message.severity]}>[{message.severity}]</span>
                            <span
                                style={`white-space: pre-wrap; word-break: break-all; ${messageStyle[message.severity]}`}
                                >{message.text}</span
                            >
                        </div>
                    {/each}
                {/if}
            </div>
        </CardBody>
    </Card>
</div>
