// Bottleneko.Client/src/features/proxies/ProxySettings.tsx
import './proxy.scss';
import { useCallback, useState } from 'react';
import { Dropdown } from 'react-bootstrap';
import { ProxyDto } from '../api/dtos.gen';
import { TableRow } from '../../components/table';
import ScrollableTable from '../../components/table/ScrollableTable';
import IconButton from '../../components/IconButton';
import { HamburgerMenu } from '../../components/HamburgerMenu';
import InlineIcon from '../../components/InlineIcon';
import { useEntityDeletion } from '../../app/hooks';
import { ProxyEntityConfig, useProxies } from './context';
import ProxyEditor from './ProxyEditor';
import { ProxyState } from './ProxiesProvider';
import { proxyTypeMap } from '.';

export default function ProxySettings() {
    const proxies = useProxies();
    const [editorState, setEditorState] = useState({ shown: false, editing: null as (ProxyDto | null) });
    const { deleteEntity, dialog } = useEntityDeletion<ProxyEntityConfig>(proxies);

    const columns = [
        { id: 'name', header: 'Proxy Name' },
        { id: 'type', header: 'Type', style: { width: '5em' } },
        { id: 'address', header: 'Address', style: { width: '15em' } },
        { id: 'actions', header: '', style: { width: '5em' } },
    ];

    const renderRow = useCallback((proxy: ProxyState): TableRow => ({
        id: proxy.data.id,
        className: 'proxy-list-row',
        onClick: () => { setEditorState({ shown: true, editing: proxy.data }); },
        columns: {
            name: {
                content: proxy.data.name,
                className: 'text-collapse',
                style: { verticalAlign: 'middle' },
            },
            type: {
                content: proxyTypeMap[proxy.data.type].name,
                style: { verticalAlign: 'middle' },
            },
            address: {
                content: `${proxy.data.hostname}:${proxy.data.port.toString()}`,
                className: 'font-monospace text-collapse',
                style: { verticalAlign: 'middle' },
            },
            actions: {
                content: (
                    <div className="w-100 d-flex justify-content-end gap-2">
                        <Dropdown>
                            <Dropdown.Toggle as={HamburgerMenu} />
                            <Dropdown.Menu>
                                <Dropdown.Item as="button" onClick={() => { setEditorState({ shown: true, editing: proxy.data }); }}>
                                    <InlineIcon icon="gear-fill" style={{ marginRight: '0.5em' }} />
                                    Edit
                                </Dropdown.Item>
                                <Dropdown.Divider />
                                <Dropdown.Item as="button" onClick={() => { deleteEntity(proxy); }}>
                                    <InlineIcon icon="trash3-fill" style={{ marginRight: '0.5em' }} />
                                    Delete
                                </Dropdown.Item>
                            </Dropdown.Menu>
                        </Dropdown>
                    </div>
                ),
                onClick: (e) => { e.stopPropagation(); },
            },
        },
    }), [deleteEntity]);

    return (
        <>
            {dialog}

            <ProxyEditor
                show={editorState.shown}
                proxy={editorState.editing}
                onSuccess={(proxy) => {
                    if (editorState.editing) {
                        void proxies?.state.list?.find(p => p.data.id === proxy.id)?.update(proxy);
                    }
                    else {
                        void proxies?.actions.add(proxy);
                    }
                    setEditorState({ shown: false, editing: proxy });
                }}
                onCancel={() => { setEditorState({ shown: false, editing: editorState.editing }); }}
            />

            <div className="proxy-list" style={{ height: '500px' }}>
                <ScrollableTable
                    columns={columns}
                    render={renderRow}
                    data={proxies?.state.list}
                    style={{ minWidth: '500px' }}
                    placeholder={() => <em className="text-secondary fst-italic">(no proxies)</em>}
                    title="Proxy servers"
                    highlightHeader
                >
                    <ScrollableTable.HeaderExtra position="end">
                        <IconButton icon="plus-lg" tooltip="Add proxy server" variant="dark" onClick={() => { setEditorState({ shown: true, editing: null }); }} />
                    </ScrollableTable.HeaderExtra>
                </ScrollableTable>
            </div>
        </>
    );
}

// Bottleneko.Client/src/lib/features/proxies/ProxySettings.svelte
<script lang="ts">
    import './style.scss';
    import type { ProxyDto } from '$lib/api/dtos.gen';
    import EntityDeletionDialog from '$lib/components/EntityDeletionDialog.svelte';
    import IconButton from '$lib/components/IconButton.svelte';
    import { type TypedDataTable } from '$lib/components/DataTable';
    import DataTable from '$lib/components/DataTable.svelte';
    import { Proxies } from '../proxies';
    import type { LocalProxy, ProxiesProvider } from '../proxies/provider.svelte';
    import ProxyEditor from './ProxyEditor.svelte';
    import ProxyListRowRenderer from './ProxyListRowRenderer.svelte';
    import type { TableType, RendererProps } from './ProxySettings';

    let editorState = $state({ shown: false, editing: null as ProxyDto | null });

    let deletingProxy: LocalProxy | null = $state(null);
    let isDeleting = $state(false);

    const ondelete = async () => {
        if (deletingProxy) {
            try {
                isDeleting = true;
                await Proxies.provider?.delete(deletingProxy);
            } finally {
                isDeleting = false;
                deletingProxy = null;
            }
        }
    };

    const ProxyListTable = DataTable as TypedDataTable<TableType>;
    const rendererProps: RendererProps = (props) => {
        return {
            ...props,
            onedit(proxy) {
                editorState = { shown: true, editing: proxy.data };
            },
            ondelete(proxy) {
                deletingProxy = proxy;
            },
        };
    };
</script>

<ProxyEditor
    show={editorState.shown}
    proxy={editorState.editing}
    onsuccess={async (proxy: ProxiesProvider['$update']) => {
        if (editorState.editing) {
            const localProxy = Proxies.provider?.list?.find((p) => p.data.id === editorState.editing?.id);
            if (localProxy) {
                await localProxy.update(proxy);
            }
        } else {
            await Proxies.provider?.add(proxy);
        }
        editorState = { shown: false, editing: null };
    }}
    onclose={() => (editorState = { shown: false, editing: editorState.editing })}
/>

<div class="proxy-list" style:height="500px">
    <EntityDeletionDialog
        item={deletingProxy}
        type-name="proxy"
        loading={isDeleting}
        {ondelete}
        onclose={() => (deletingProxy = null)}
    />

    <ProxyListTable
        title="Proxy servers"
        highlight-header
        variant="small-table"
        renderer={ProxyListRowRenderer}
        {rendererProps}
        columns={{
            name: { header: 'Proxy Name' },
            type: { header: 'Type', style: 'width: 5em' },
            address: { header: 'Address', style: 'width: 15em' },
            actions: { header: '', style: 'width: 5em' },
        }}
        rows={Proxies.provider?.list?.map((proxy) => ({
            id: proxy.data.id,
            onclick: () => (editorState = { shown: true, editing: proxy.data }),
            cells: {
                name: {
                    class: 'text-collapse',
                    style: 'vertical-align: middle',
                },
                type: {
                    style: 'vertical-align: middle',
                },
                address: {
                    style: 'vertical-align: middle',
                },
                actions: {},
            },
            data: proxy,
        }))}
    >
        {#snippet placeholder()}
            <em class="text-secondary fst-italic">(no proxies)</em>
        {/snippet}

        {#snippet endHeaderExtra()}
            <IconButton
                icon="plus-lg"
                tooltip="Add proxy server"
                variant="dark"
                onclick={() => (editorState = { shown: true, editing: null })}
            />
        {/snippet}
    </ProxyListTable>
</div>
