// Bottleneko.Client/src/features/proxies/ProxyEditor.tsx
import * as yup from 'yup';
import { useEffect, useRef, useState } from 'react';
import { Form } from 'react-bootstrap';
import { Formik } from 'formik';
import ModalDialog from '../../components/modal-dialog/ModalDialog';
import { ProxyDto, ProxyType } from '../api/dtos.gen';
import ProxyTypePicker from './ProxyTypePicker';

const schema = yup.object().shape({
    name: yup.string().label('Name').required(),
    type: yup.mixed<ProxyType>().oneOf(Object.values(ProxyType)).required(),
    hostname: yup.string().label('Hostname').required(),
    port: yup.number().label('Port').min(1).max(65535).required(),
    isAuthRequired: yup.boolean(),
    username: yup.string().label('Username').when('isAuthRequired', {
        is: true,
        then: schema => schema.required(),
    }),
    password: yup.string().label('Password').when(['isAuthRequired', 'type'], {
        is: (isAuthRequired: boolean, type: ProxyType) => isAuthRequired && type !== ProxyType.Socks4 && type !== ProxyType.Socks4a,
        then: schema => schema.required(),
    }),
});

type ProxyEditorStage =
    { id: 'select-type'; type: ProxyType } |
    { id: 'edit'; proxy: ProxyDto; isNew: boolean };

export default function ProxyEditor({ show, proxy, onSuccess, onCancel }: { show: boolean; proxy: ProxyDto | null; onSuccess: (proxy: ProxyDto) => void; onCancel: () => void }) {
    const [stage, setStage] = useState<ProxyEditorStage>({ id: 'select-type', type: ProxyType.Http });

    const formRef = useRef<HTMLFormElement>(null);

    const oldShowRef = useRef(false);
    useEffect(() => {
        if (show && !oldShowRef.current) {
            setStage(proxy ? { id: 'edit', proxy, isNew: false } : { id: 'select-type', type: ProxyType.Http });
        }
        oldShowRef.current = show;
    }, [stage, show, proxy]);

    switch (stage.id) {
        case 'select-type':
            return (
                <ModalDialog
                    title="Proxy type"
                    show={show}
                    onCancel={onCancel}
                >
                    <ProxyTypePicker
                        type={stage.type}
                        onChange={(type) => { setStage({ ...stage, type }); }}
                    />

                    <ModalDialog.Button onClick={onCancel} variant="secondary">Back</ModalDialog.Button>
                    <ModalDialog.Button onClick={() => { setStage({ id: 'edit', proxy: { id: '', name: '', hostname: '', port: 1080, type: stage.type, isAuthRequired: false, username: '', password: '' }, isNew: true }); }}>Next</ModalDialog.Button>
                </ModalDialog>
            );
            break;

        case 'edit':
            return (
                <ModalDialog
                    title="Proxy configuration"
                    show={show}
                    onCancel={onCancel}
                >
                    <ModalDialog.Button
                        onClick={() => {
                            if (stage.isNew) {
                                setStage({ id: 'select-type', type: stage.proxy.type });
                            }
                            else {
                                onCancel();
                            }
                        }}
                        variant="secondary"
                    >
                        Back
                    </ModalDialog.Button>
                    <ModalDialog.Button onClick={() => { formRef.current?.requestSubmit(); }}>Save</ModalDialog.Button>

                    <Formik validationSchema={schema} onSubmit={(proxy) => { onSuccess(proxy); }} initialValues={stage.proxy} enableReinitialize={true} validateOnChange={false}>
                        {({ handleSubmit, handleChange, values, setFieldValue, errors }) => (
                            <Form
                                noValidate
                                onSubmit={(e) => {
                                    e.preventDefault();
                                    e.stopPropagation();
                                    handleSubmit();
                                }}
                                className="d-flex flex-column p-2"
                                style={{ gap: '1rem' }}
                                ref={formRef}
                            >
                                <Form.Group>
                                    <Form.Label>Proxy name</Form.Label>
                                    <Form.Control name="name" value={values.name} onChange={handleChange} isInvalid={!!errors.name} autoComplete="off" />
                                    <Form.Text muted>
                                        Description for the proxy
                                    </Form.Text>
                                    <Form.Control.Feedback type="invalid">
                                        {errors.name}
                                    </Form.Control.Feedback>
                                </Form.Group>

                                <Form.Group>
                                    <Form.Label>Hostname</Form.Label>
                                    <Form.Control name="hostname" value={values.hostname} onChange={handleChange} isInvalid={!!errors.hostname} autoComplete="off" />
                                    <Form.Text muted>
                                        Hostname or IP address of the proxy
                                    </Form.Text>
                                    <Form.Control.Feedback type="invalid">
                                        {errors.hostname}
                                    </Form.Control.Feedback>
                                </Form.Group>

                                <Form.Group>
                                    <Form.Label>Port</Form.Label>
                                    <Form.Control name="port" type="number" value={values.port} onChange={handleChange} isInvalid={!!errors.port} autoComplete="off" />
                                    <Form.Text muted>
                                        Port of the proxy
                                    </Form.Text>
                                    <Form.Control.Feedback type="invalid">
                                        {errors.port}
                                    </Form.Control.Feedback>
                                </Form.Group>

                                <Form.Switch
                                    name="isAuthRequired"
                                    label="Use authentication"
                                    checked={values.isAuthRequired}
                                    onChange={() => { void setFieldValue('isAuthRequired', !values.isAuthRequired); }}
                                />
                                <Form.Group>
                                    <Form.Label>Username</Form.Label>
                                    <Form.Control name="username" value={values.username} onChange={handleChange} isInvalid={!!errors.username} autoComplete="off" disabled={!values.isAuthRequired} />
                                    <Form.Control.Feedback type="invalid">
                                        {errors.username}
                                    </Form.Control.Feedback>
                                </Form.Group>

                                {
                                    values.type !== ProxyType.Socks4 && values.type !== ProxyType.Socks4a
                                        ? (
                                                <Form.Group>
                                                    <Form.Label>Password</Form.Label>
                                                    <Form.Control name="password" type="password" value={values.password} onChange={handleChange} isInvalid={!!errors.password} autoComplete="off" disabled={!values.isAuthRequired} />
                                                    <Form.Control.Feedback type="invalid">
                                                        {errors.password}
                                                    </Form.Control.Feedback>
                                                </Form.Group>
                                            )
                                        : <></>
                                }
                            </Form>
                        )}
                    </Formik>
                </ModalDialog>
            );

        default:
            return <></>;
    }
}

// Bottleneko.Client/src/lib/features/proxies/ProxyEditor.svelte
<script lang="ts">
    import type { ProxyDto } from '$lib/api/dtos.gen';
    import ModalDialog from '$lib/components/ModalDialog.svelte';
    import { FormState } from '$lib/FormState.svelte';
    import { Alert, Button, Form, FormFeedback, FormGroup, FormText, Input, Label } from '@sveltestrap/sveltestrap';
    import { proxyTypes } from './provider.svelte';
    import { FormSchema, type Props, type ProxyEditorStage } from './ProxyEditor';
    import { ChangesTracker } from '$lib';

    const props: Props = $props();
    const formState = $derived(new FormState(FormSchema, props.proxy ?? undefined, props.onsuccess));
    let stage: ProxyEditorStage = $state({ id: 'select-type', type: 'Http' });

    const changesTracker = new ChangesTracker<ProxyDto | null>((_, value) => {
        if (!value) {
            stage = { id: 'select-type', type: 'Http' };
        } else {
            stage = { id: 'edit', isNew: false, proxy: value };
            formState.data = $state.snapshot(value);
        }
    }, props.proxy);
    $effect(() => {
        changesTracker.set(props.proxy);
    });
</script>

<ModalDialog
    title={stage.id === 'select-type' ? 'Proxy type' : 'Proxy settings'}
    show={props.show}
    onclose={props.onclose}
    size="lg"
>
    {#if stage.id === 'select-type'}
        {#each proxyTypes as proxyType (proxyType.type)}
            <FormGroup>
                <Input
                    type="radio"
                    label={proxyType.name}
                    value={proxyType.type}
                    bind:group={formState.data.type}
                    disabled={formState.isLoading}
                />
                <FormText>
                    {proxyType.description}
                </FormText>
            </FormGroup>
        {/each}
    {:else if stage.id === 'edit'}
        <Form
            novalidate
            onsubmit={async (e: SubmitEvent) => {
                await formState.submit(e);
            }}
            class="d-flex flex-column p-2"
            style="gap: 1rem"
        >
            {#if formState.error}
                <Alert color="danger">
                    {formState.error}
                </Alert>
            {/if}
            <FormGroup>
                <Label>Proxy name</Label>
                <Input
                    bind:value={formState.data.name}
                    invalid={!!formState.validationErrors.name}
                    autocomplete="off"
                    disabled={formState.isLoading}
                />
                <FormText>Description for the proxy</FormText>
                <FormFeedback valid={!formState.validationErrors.name}>
                    {formState.validationErrors.name}
                </FormFeedback>
            </FormGroup>

            <FormGroup>
                <Label>Hostname</Label>
                <Input
                    bind:value={formState.data.hostname}
                    invalid={!!formState.validationErrors.hostname}
                    autocomplete="off"
                    disabled={formState.isLoading}
                />
                <FormText>Hostname or IP address of the proxy</FormText>
                <FormFeedback valid={!formState.validationErrors.hostname}>
                    {formState.validationErrors.hostname}
                </FormFeedback>
            </FormGroup>

            <FormGroup>
                <Label>Port</Label>
                <Input
                    type="number"
                    bind:value={formState.data.port}
                    invalid={!!formState.validationErrors.port}
                    autocomplete="off"
                    disabled={formState.isLoading}
                />
                <FormText>Port of the proxy</FormText>
                <FormFeedback valid={!formState.validationErrors.port}>
                    {formState.validationErrors.port}
                </FormFeedback>
            </FormGroup>

            <Input
                type="checkbox"
                name="isAuthRequired"
                label="Use authentication"
                bind:checked={formState.data.isAuthRequired}
                disabled={formState.isLoading}
            />
            <FormGroup>
                <Label>Username</Label>
                <Input
                    bind:value={formState.data.username}
                    invalid={!!formState.validationErrors.username}
                    autocomplete="off"
                    disabled={!formState.data.isAuthRequired || formState.isLoading}
                />
                <FormFeedback valid={!formState.validationErrors.username}>
                    {formState.validationErrors.username}
                </FormFeedback>
            </FormGroup>

            {#if formState.data.type !== 'Socks4' && formState.data.type !== 'Socks4a'}
                <FormGroup>
                    <Label>Password</Label>
                    <Input
                        type="password"
                        bind:value={formState.data.password}
                        invalid={!!formState.validationErrors.password}
                        autocomplete="off"
                        disabled={!formState.data.isAuthRequired || formState.isLoading}
                    />
                    <FormFeedback valid={!formState.validationErrors.password}>
                        {formState.validationErrors.password}
                    </FormFeedback>
                </FormGroup>
            {/if}
        </Form>
    {/if}

    {#snippet footer()}
        {#if stage.id === 'select-type'}
            {@const next = () => {
                if (stage.id === 'select-type') {
                    stage = {
                        id: 'edit',
                        proxy: {
                            id: '',
                            name: '',
                            hostname: '',
                            port: 1080,
                            type: stage.type,
                            isAuthRequired: false,
                            username: '',
                            password: '',
                        },
                        isNew: true,
                    };
                }
            }}

            <Button onclick={props.onclose} color="secondary">Back</Button>
            <Button onclick={next} color="primary" disabled={!formState.data.type}>Next</Button>
        {:else if stage.id === 'edit'}
            {@const back = () => {
                if (stage.id === 'edit' && stage.isNew) {
                    stage = { id: 'select-type', type: stage.proxy.type };
                } else {
                    props.onclose?.();
                }
            }}

            <Button onclick={back} color="secondary">Back</Button>
            <Button onclick={() => formState.submit()} color="primary">Save</Button>
        {/if}
    {/snippet}
</ModalDialog>
