// Bottleneko.Client/src/features/users/UserEditor.tsx
import { Formik } from 'formik';
import * as yup from 'yup';
import { Button, Form } from 'react-bootstrap';
import { UserDto } from '../api/dtos.gen';

export const EditedUserSchema = yup.object().shape({
    login: yup.string().default('').required('Username cannot be empty'),
    password: yup.string().default(''),
});

export type EditedUser = yup.InferType<typeof EditedUserSchema>;

export default function UserEditor({ user, loading = false, newUser, onValidated }: { user?: UserDto; newUser: boolean; loading?: boolean; onValidated?: (formData: EditedUser) => void }) {
    return (
        <Formik validationSchema={EditedUserSchema} onSubmit={onValidated ?? ((_) => { void _; })} initialValues={user ? { login: user.displayName, password: '' } : EditedUserSchema.getDefault()} validateOnChange={false}>
            {({ handleSubmit, handleChange, values, errors }) => (
                <Form
                    noValidate
                    onSubmit={(e) => {
                        e.preventDefault();
                        e.stopPropagation();
                        handleSubmit();
                    }}
                >
                    <Form.Group className="mb-3">
                        <Form.Label>Username</Form.Label>
                        <Form.Control name="login" value={values.login} onChange={handleChange} isInvalid={!!errors.login} disabled={loading} autoComplete="off" />
                        <Form.Text muted>
                            Usernames are case-insensitive and must be unique among all users.
                        </Form.Text>
                        <Form.Control.Feedback type="invalid">
                            {errors.login}
                        </Form.Control.Feedback>
                    </Form.Group>

                    <Form.Group className="mb-3">
                        <Form.Label>{newUser ? 'Password' : 'New Password'}</Form.Label>
                        <Form.Control name="password" type="password" value={values.password} onChange={handleChange} isInvalid={!!errors.password} disabled={loading} autoComplete="off" />
                        {
                            newUser
                                ? <></>
                                : (
                                        <Form.Text muted>
                                            Leave empty to keep the current password.
                                        </Form.Text>
                                    )
                        }
                        <Form.Control.Feedback type="invalid">
                            {errors.password}
                        </Form.Control.Feedback>
                    </Form.Group>

                    <hr />

                    <div className="d-flex justify-content-center">
                        <Button size="lg" style={{ width: 'min(15%, 400px)', minWidth: '200px' }} type="submit" disabled={loading}>{newUser ? 'Add' : 'Save'}</Button>
                    </div>
                </Form>
            )}
        </Formik>
    );
}

// Bottleneko.Client/src/lib/features/users/UserEditor.svelte
<script lang="ts">
    import { ChangesTracker } from '$lib';
    import { type UserDto } from '$lib/api/dtos.gen';
    import ModalDialog from '$lib/components/ModalDialog.svelte';
    import { FormState } from '$lib/FormState.svelte';
    import { Alert, Button, Form, FormFeedback, FormGroup, FormText, Input, Label } from '@sveltestrap/sveltestrap';
    import * as yup from 'yup';
    import type { Props } from './UserEditor';

    const props: Props = $props();

    const passwordField = $derived(
        props.user ? yup.string().default('') : yup.string().default('').required('Password cannot be empty'),
    );

    const FormSchema = $derived(
        yup.object().shape({
            login: yup.string().default('').required('Username cannot be empty'),
            password: passwordField,
        }),
    );

    const formState = $derived(
        new FormState(FormSchema, { ...FormSchema.getDefault(), ...(props.user ?? {}) }, async (data) => {
            await props.onsuccess?.(data);
        }),
    );

    const userChangesTracker = new ChangesTracker<UserDto | null>((_, value) => {
        if (!value) {
            formState.data = FormSchema.getDefault();
        } else {
            formState.data = { login: value.login, password: '' };
        }
        formState.clearErrors();
    }, props.user);

    $effect(() => {
        userChangesTracker.set(props.user);
    });

    const showChangesTracker = new ChangesTracker<boolean>((_, value) => {
        if (value) {
            userChangesTracker.forceUpdate(props.user);
        }
    }, props.show);
    $effect(() => {
        showChangesTracker.set(props.show);
    });
</script>

<ModalDialog title="User settings" show={props.show} onclose={props.onclose} size="lg">
    <Form
        novalidate
        onsubmit={async (e: SubmitEvent) => {
            await formState.submit(e);
        }}
        class="d-flex flex-column p-2"
        style="gap: 1rem"
    >
        {#if formState.error}
            <Alert color="danger">
                {formState.error}
            </Alert>
        {/if}

        <FormGroup>
            <Label>Username</Label>
            <Input
                bind:value={formState.data.login}
                invalid={!!formState.validationErrors.login}
                autocomplete="off"
                disabled={formState.isLoading}
            />
            <FormText>Usernames are case-insensitive and must be unique among all users.</FormText>
            <FormFeedback valid={!formState.validationErrors.login}>
                {formState.validationErrors.login}
            </FormFeedback>
        </FormGroup>

        <FormGroup>
            <Label>Password</Label>
            <Input
                type="password"
                bind:value={formState.data.password}
                invalid={!!formState.validationErrors.password}
                autocomplete="off"
                disabled={formState.isLoading}
            />
            <FormText>
                {#if props.user}
                    Leave empty to keep the current password.
                {:else}
                    Password must be non-empty.
                {/if}
            </FormText>
            <FormFeedback valid={!formState.validationErrors.password}>
                {formState.validationErrors.password}
            </FormFeedback>
        </FormGroup>
    </Form>

    {#snippet footer()}
        <Button onclick={() => props.onclose?.()} color="secondary">Back</Button>
        <Button onclick={() => formState.submit()} color="primary">Save</Button>
    {/snippet}
</ModalDialog>
